package locators;

public interface ERO_Routing_Locators {
	
	public static String SelectERO = "Select Ero routing>//li[@data-item-label='ERO Routing']";
	public static String Routing_GlobalSearch = "Ero routing globalsearch>//button[@id='ERU-ERU_toolbar-btnTblJdlgSearch']";
	public static String ERO_popup_ok = "Ero routing ok>//h2[text()='ERO Routing']/following::button[text()='Ok']";
	public static String Routing_Edit = "Ero routing edit>//button[@id='ERU-ERU_toolbar-btnTblEdit']";
	public static String Origin_1 = "Grid origin 1>(//div[@col-id='origin'])[2]";
	public static String Routing_Save = "Ero routing save>//button[@id='ERU-ERU_toolbar-btnsave']";
	public static String Routing_Cancel = "Ero routing cancel>//button[@id='ERU-ERU_toolbar-btnTblCancel']";
	public static String Routing_ID = "Routing ID>//input[@id='ERU-ERU_txtID']";
	public static String Routing_Tab = "Routing Tab>(//label[text()='ERO Routing'])[1]";
	public static String Route_detailscount = "Route details count>//input[@id='ERU-ERU_txtRouteCnt']";
	public static String ERO_ID = "ERO ID>//input[@id='ERU-ERU_txtID']";

	public static String UnavailableRoute_scount = "Unavailable Route count>//input[@id='ERU-ERU_txtUnRouteCnt']";

	public static String Popup_text = "Error message text>(//h2[text()='ERO Routing']/following::span)[2]";
	public static String Optimizer = "Optimizer>//button[@id='ERU-ERU_btnOptimizer']";
	public static String Optimizer_Ok = "Optimizer_Ok>//button[@id='ERU_btnOk']";
	public static String ERO_Popup_Ok = "Ero popup ok>//h2[text()='ERO Routing']/following::button";
	public static String ERO_Popup_Ok2 = "Ero popup ok>(//h2[text()='ERO Routing']/following::button)[2]";
	public static String ERO_Treetable = "Ero Tree table>//div[@id='ERU-ERU_treeTable1_nfr_toolpanel_li_id']";
	public static String Version = "Version field>//label[contains(text(),'Version :')]";
	public static String ERO_Edit = "Ero Edit>//button[@id='ERU-ERU_toolbar-btnTblEdit']";
	public static String ERO_save = "Ero Save>//button[@id='ERU-ERU_toolbar-btnsave']";
	public static String ERO_Tab = "Ero Tab>//label[text()='ERO Routing']";
	public static String ERO_OriginGrid = "Origin grid3 value>(//div[@col-id='origin'])[3]";
	public static String ERO_Warningicon = "ERO_Warningicon>(//h2[text()='ERO Routing']/following::span)[1]";
	public static String ERO_Warning_Message = "ERO_Warningicon message>(//h2[text()='ERO Routing']/following::span)[2]";
	public static String Refresh_Routing = "Refresh routing>//button[@id='ERU-ERU_btnRefreshRouting']";
	public static String Recalculate_Routing = "Recalculate routing>//button[@id='ERU-ERU_btnCalculate']";
	public static String ERO_cancel = "Ero Cancel>//button[@id='ERU-ERU_toolbar-btnTblCancel']";
	public static String Calculate_No = "Ero recalculate popup no>//h2[text()='ERO Routing']/following::button[text()='No']";
	public static String Calculate_Yes = "Ero recalculate popup yes>//h2[text()='ERO Routing']/following::button[text()='Yes']";
	public static String Grid1_Checkbox = "ERO routing grid 1 checkbox>((//div[@col-id='nfr_sel_col'])[2]//div)[3]";

	public static String ERO_Costsplitup = "Ero cost splitup>//button[@id='ERU-ERU_btnHideCostColumns']";
	public static String ERO_Filter = "ERO_Filter>(//*[@class='ag-icon ag-icon-columns'])[2]";
	public static String ERO_Filter_box = "ERO_Filter_box>(//input[@aria-label='Toggle Select All Columns'])[2]";
	public static String ERO_Filter_Search = "ERO_Filter_Search>(//input[@aria-label='Select Toggle Selection'])[1]";
	public static String ERO_Filter_Origin = "ERO_Filter_Origin>(//input[@aria-label='Origin Toggle Selection'])[1]";
	public static String ERO_Filter_Delivery = "ERO_Filter_Delivery>(//input[@aria-label='Delivery Toggle Selection'])[1]";
	public static String ERO_Size_Type = "ERO_Size_Type>(//input[@aria-label='Size Type Toggle Selection'])[1]";
	public static String ERO_Cost = "ERO_Cost>(//input[@aria-label='Cost (USD) Toggle Selection'])[1]";
	public static String ERO_Main_Service = "ERO_Cost>(//input[@aria-label='Main Service Toggle Selection'])[1]";
	public static String ERO_Origin_Mode = "ERO_Origin_Mode>(//input[@aria-label='Origin Mode Toggle Selection'])[1]";
	public static String ERO_POL = "ERO_POL>(//input[@aria-label='POL Toggle Selection'])[1]";
	public static String ERO_POL_Terminal = "ERO_POL_Terminal>(//input[@aria-label='POL Terminal Toggle Selection'])[1]";
	public static String ERO_POL_Service = "ERO_POL_Service>(//input[@aria-label='POL Service Toggle Selection'])[1]";
	public static String ERO_Trans1 = "ERO_Trans1>(//input[@aria-label='Trans1 Toggle Selection'])[1]";
	public static String ERO_Trans1_ser = "ERO_Trans1_ser>(//input[@aria-label='Trans1 Ser Toggle Selection'])[1]";
	public static String ERO_Trans2 = "ERO_Trans2>(//input[@aria-label='Trans2 Toggle Selection'])[1]";
	public static String ERO_Trans2_ser = "ERO_Trans2_ser>(//input[@aria-label='Trans2 Ser Toggle Selection'])[1]";
	public static String ERO_Trans3 = "ERO_Trans3>(//input[@aria-label='Trans3 Toggle Selection'])[1]";
	public static String ERO_Trans3_ser = "ERO_Trans3_ser>(//input[@aria-label='Trans3 Ser Toggle Selection'])[1]";
	public static String ERO_POD = "ERO_POD>(//input[@aria-label='POD Toggle Selection'])[1]";
	public static String ERO_POD_Terminal = "ERO_POD_Terminal>(//input[@aria-label='POD Terminal Toggle Selection'])[1]";
	public static String ERO_Delivery_Mode = "ERO_Delivery_Mode>(//input[@aria-label='Delivery Mode Toggle Selection'])[1]";
	public static String ERO_Transit_Days = "ERO_Transit_Days>(//input[@aria-label='Transit Days Toggle Selection'])[1]";
	public static String ERO_Missing_Cost = "ERO_Missing_Cost>(//input[@aria-label='Missing Cost Toggle Selection'])[1]";
	public static String ERO_Routing_From = "ERO_Routing_From>(//input[@aria-label='Routing From Toggle Selection'])[1]";
	public static String ERO_Load_Cost = "ERO_Load_Cost>(//input[@aria-label='Load Cost Toggle Selection'])[1]";
	public static String ERO_Disch_Cost = "ERO_Disch_Cost>(//input[@aria-label='Disch Cost Toggle Selection'])[1]";
	public static String ERO_Ts1_Load_Cost = "ERO_Ts1_Load_Cost>(//input[@aria-label='TS1 Load Cost Toggle Selection'])[1]";
	public static String ERO_Ts2_Load_Cost = "ERO_Ts2_Load_Cost>(//input[@aria-label='TS2 Load Cost Toggle Selection'])[1]";
	public static String ERO_Ts3_Load_Cost = "ERO_Ts3_Load_Cost>(//input[@aria-label='TS3 Load Cost Toggle Selection'])[1]";
	public static String ERO_TS1_Disch_Cost = "ERO_TS1_Disch_Cost>(//input[@aria-label='TS1 Disch Cost Toggle Selection'])[1]";
	public static String ERO_TS2_Disch_Cost = "ERO_TS2_Disch_Cost>(//input[@aria-label='TS2 Disch Cost Toggle Selection'])[1]";
	public static String ERO_TS3_Disch_Cost = "ERO_TS3_Disch_Cost>(//input[@aria-label='TS3 Disch Cost Toggle Selection'])[1]";
	public static String ERO_Feeder_Cost_1 = "ERO_Feeder_Cost_1>(//input[@aria-label='Feeder Cost 1 Toggle Selection'])[1]";
	public static String ERO_Feeder_1_terms = "ERO_Feeder_1_terms>(//input[@aria-label='Feeder 1 Terms Toggle Selection'])[1]";
	public static String ERO_Feeder_Cost_2 = "ERO_Feeder_Cost_2>(//input[@aria-label='Feeder Cost 2 Toggle Selection'])[1]";
	public static String ERO_Feeder_2_terms = "ERO_Feeder_2_terms>(//input[@aria-label='Feeder 2 Terms Toggle Selection'])[1]";
	public static String ERO_Feeder_Cost_3 = "ERO_Feeder_Cost_3>(//input[@aria-label='Feeder Cost 3 Toggle Selection'])[1]";
	public static String ERO_Feeder_3_terms = "ERO_Feeder_3_terms>(//input[@aria-label='Feeder 3 Terms Toggle Selection'])[1]";
	public static String ERO_Load_Haulage = "ERO_Load_Haulage>(//input[@aria-label='Load Haulage Cost Toggle Selection'])[1]";
	public static String ERO_Disch_Haulage = "ERO_Disch_Haulage>(//input[@aria-label='Disch Haulage Cost Toggle Selection'])[1]";
	public static String ERO_DPH_Origin_Haulage = "ERO_DPH_Origin_Haulage>(//input[@aria-label='DPH Origin Cost Toggle Selection'])[1]";
	public static String ERO_DPH_Origin_Destination_Cost = "ERO_DPH_Origin_Destination_Cost>(//input[@aria-label='DPH Destination Cost Toggle Selection'])[1]";
	public static String ERO_LTC_Origin_Cost = "ERO_LTC_Origin_Cost>(//input[@aria-label='LCT Origin Cost Toggle Selection'])[1]";
	public static String ERO_LTC_Destination_Cost = "ERO_LTC_Destination_Cost>(//input[@aria-label='LCT Destination Cost Toggle Selection'])[1]";
	public static String ERO_On_Hire_Cost = "ERO_On_Hire_Cost>(//input[@aria-label='On-Hire Cost Toggle Selection'])[1]";
	public static String ERO_OFf_Hire_Cost = "ERO_OFf_Hire_Cost>(//input[@aria-label='Off-Hire Cost Toggle Selection'])[1]";
	public static String ERO_Service_Destination_Cost = "ERO_Service_Destination_Cost>(//input[@aria-label='In Service Destination Cost Toggle Selection'])[1]";
	public static String ERO_Un_available_Route = "ERO_Un_available_Route>//*[text()='Un Available Route']";
	public static String ERO_TreeTable = "TreeTable>//div[@id='ERU-ERU_treeTable1_nfr_toolpanel_li_id']";
	public static String Ero_Codition_Filter = "Ero_Codition_Filter>//*[@id='ERU-ERU_treeTable1_conditionFilter_id']";
	public static String Ero_Codition_Filter_Input_Field = "Ero_Codition_Filter_Input_Field>//input[@aria-label='Select Filter Input']";
	public static String ERO_Distinct_Filter = "ERO_Distinct_Filter>//*[@id='ERU-ERU_treeTable1_setDistinctFilter_id']";
	public static String ERO_SVM = "ERO_SVM>(//span[text()='SVM'])[2]";
	public static String ERO_SVM1 = "ERO_SVM>(//span[text()='SVM'])[1]";
	public static String SVM_dropdown="SVM_dropdown>(//span[@class='ui-tree-toggler ui-icon ui-icon-triangle-1-e'])[1]";
	public static String ERO_SVM_data_Grid = "ERO_SVM_data_Grid>(//div[@col-id='nfr_sel_col'])[2]";
	public static String ERO_AFR_Option = "ERO_AFR_Option>//span[text()='AFR']";
	public static String ERO_Total_Count = "ERO_Total_Count>//*[@id='ERU-ERU_treeTable1_records_lbl_cnt']";
	public static String ERO_Un_Total_Count = "ERO_Total_Count>//*[@id='ERU-ERU_treeTable2_records_lbl_cnt']";
    public static String Ero_Afr_drop="Ero_Afr_drop>(//div[@id='ERU-ERU_tree']//following::span)[4]";
	public static String EPO_map = "EPO_map>//*[@id='ERU-ERU_btnViewMap']";
	public static String EPO_map_Id_Field = "EPO_map_Id_Field>//input[@id='MAV-MAV_txtDeficitSurplusID']";
	public static String EPO_edit = "EPO_edit>//button[@id='ERU-ERU_toolbar-btnTblEdit']";
	public static String EPO_Save = "EPO_Save>//button[@id='ERU-ERU_toolbar-btnsave']";
	public static String EPO_Save_Pop = "EPO_Save_Pop>//span[text()='No changes made to update']";
	public static String Epo_save_OK = "Epo_save_OK>//*[text()='ERO Routing']//following::button[text()='Ok']";
	public static String EPO_excel = "EPO_excel>//a[@id='ERU-ERU_treeTable1_exportExcelxlsx_id']";
	public static String EPO_Missing_cost = ">//button[@id='ERU-ERU_btnMissingCost']";
	public static String EPO_LOCATION_FIELD = "EPO_LOCATION_FIELD>(//*[@id='ERU_treeTableLC_head']//following::input)[1]";
	public static String EPO_equipment_Type = "EPO_equipment_Type>(//*[@id='ERU_treeTableLC_head']//following::input)[3]";
	public static String EPO_RefreshRouting = "EPO_RefreshRouting>//button[@id='ERU-ERU_btnRefreshRouting']";
	public static String EPO_Route_Details = "EPO_Route_Details>//a[text()='Route Details']";
	public static String EPO_Missing_coat = "EPO_Missing_coat>(//span[text()='Missing Cost'])[1]";
	public static String EPO_Color = "EPO_Color>(//div[@col-id='nfr_sel_col'])[2]";
	public static String EPO_Haulage_Routing = "EPO_Haulage_Routing>//button[@id='ERU-ERU_solverBtn5']";
	public static String EPO_Select_Filter = "EPO_Select_Filter>//div[@ref='eHeaderContainer']//div[@col-id='nfr_sel_col']//span[@ref='eMenu']";
	public static String EPO_SelectFilterOption = "EPO_SelectFilterOption>//span[@aria-label='filter']";
	public static String EPO_SelectFilterSearchBox = "EPO_SelectFilterSearchBox>//label[@ref='eSelectAllContainer']";
	public static String EPO_SearchInput="Search Input>//div[@ref='eMiniFilter']//input[@ref='eInput']";
	public static String EPO_SelectFilterSearchFirstOption = "EPO_SelectFilterSearchFirstOption>//span[text()='(Blanks)']";
	public static String EPO_Origin_Filter = "EPO_Origin_Filter>//div[@ref='eHeaderContainer']//div[@col-id='origin']//span[@ref='eMenu']";
	public static String EPO_Un_Available_Field = "EPO_Un_Available_Field>//label[@id='ERU-ERU_lblUnRoute']";
	public static String EPO_Origin_First_va = "EPO_Origin_First_va>(//span[text()='AEJEA(OW)'])[2]";
	public static String EPO_select_Display = "EPO_select_Display>(//*[@col-id='origin'])[2]";
	public static String EPO_Origin = "EPO_Origin>(//span[text()='Origin'])[1]";
	public static String EPO_Delivery = "EPO_Delivery>(//span[text()='Delivery'])[1]";
	public static String EPO_Delivery_Filter = "EPO_Origin_Filter>//div[@ref='eHeaderContainer']//div[@col-id='delivery']//span[@ref='eMenu']";
	public static String EPO_DeliveryFilterSearchFirstOption = "EPO_DeliveryFilterSearchFirstOption>(//span[text()='AEJEA(OF)'])[2]";
	public static String EPO_unavailable = "EPO_unavailable>//a[text()='Un Available Route']";
	public static String EPO_Un_Select_Filter = "EPO_Select_Filter>(//div[@ref='eHeaderContainer']//div[@col-id='nfr_sel_col']//span[@ref='eMenu'])[2]";
	public static String EPO_Un_Load = "EPO_Un_Load>//div[@ref='eHeaderContainer']//div[@col-id='sLoadregion']//span[@ref='eMenu']";
	public static String EPO_Un_Load_Input = "EPO_Un_Load_Input>(//span[text()='AFR'])[2]";
	public static String EPO_Close = "EPO_Close>(//a/i[contains(@class,'dlclose')])[2]";
	public static String ERO_Save = "ERO_Save>//*[@id='DSL-DSL_toolbar-btnsave']";
	public static String ERO_Save_ok = "ERO_Save_ok>//button[text()='Ok']";
	public static String ERO_route = "ERO_route>//button[@id='DSL-DSL_btnViewPortPair']";
	public static String ERO_Equipment_Reposition_Solve = "ERO_Equipment_Reposition_Solve>//a[text()='Equipment Reposition Solve']";
	public static String backround_color = "backround_color>//button[@id='OPT-OPT_btnRes1']";
	public static String backround_color1 = "backround_color1>//button[@id='ERU-ERU_solverBtn6']";
	public static String pink_Backroungcolor = "pink_Backroungcolor>//button[@id='OPT-OPT_btnRes2']";
	public static String optimizer_export = "optimizer_export>//button[@id='OPT-OPT_toolBar-btnTblExport']";
	public static String DY_First = "20DY_First>//*[@id='OPT-OPT_treeTable_data']/tr";
	public static String Optimizer_hc = "20DY_First>(//div[@id='OPT-OPT_tabSolve']//following::a)[1]";
	public static String Optimizer_hc_FirstVal = "Optimizer_hc_FirstVal>//*[@id='OPT-OPT_treeTable_data']/tr";
	public static String Optimizer_hh = "Optimizer_hh>(//div[@id='OPT-OPT_tabSolve']//following::a)[2]";
	public static String Optimizer_RF = "Optimizer_RF>(//div[@id='OPT-OPT_tabSolve']//following::a)[3]";
	public static String Optimizer_Dy = "Optimizer_Dy>(//div[@id='OPT-OPT_tabSolve']//following::a)[4]";
	public static String Optimizer_Hc = "Optimizer_HC>(//div[@id='OPT-OPT_tabSolve']//following::a)[5]";
	public static String Optimizer_Hr = "Optimizer_Hr>(//div[@id='OPT-OPT_tabSolve']//following::a)[6]";
	public static String Optimizer_Ot = "Optimizer_Ot>(//div[@id='OPT-OPT_tabSolve']//following::a)[7]";
	public static String surplus_qty = "surplus_qty>//input[@id='OPT-OPT_txtTotalCount']";
	public static String Deficit_qty = "Deficit>//input[@id='OPT-OPT_txtTotalCount1']";
	public static String ERS_DC_Option = "ERS_DC_Option>(//a[text()='20DC'])[1]";
	public static String Load_country = "Load_country>//div[@ref='eHeaderContainer']//div[@col-id='sLoadcounrty']//span[@ref='eMenu']";
	public static String Load_country_val = "Load_country_val>(//span[text()='AD'])[2]";
	public static String Origin = "Origin>(//div[@ref='eHeaderContainer']//div[@col-id='origin']//span[@ref='eMenu'])[2]";
	public static String Origin_val = "Origin_val>(//span[text()='ADSFC(OW)'])[2]";
	public static String Delivery = "Delivery>(//div[@ref='eHeaderContainer']//div[@col-id='delivery']//span[@ref='eMenu'])[2]";
	public static String Delivery_val = "Delivery_val>(//span[text()='AEFJR(OW)'])[2]";
	public static String Disch_val = "Delivery_val>(//span[text()='AE'])[3]";
	public static String Load_Region_val = "Delivery_val>(//span[text()='AFR'])[2]";
	public static String Dissh_Country = "Dissh_Country>//div[@ref='eHeaderContainer']//div[@col-id='sDischcounty']//span[@ref='eMenu']";
	public static String Disch_Region = "Disch_Region>//div[@ref='eHeaderContainer']//div[@col-id='sDischregion']//span[@ref='eMenu']";
	public static String Origin_val1 = "Origin_val1>(//span[text()='20DY'])[1]";
	public static String EquipmentType = "EquipmentType>(//div[@ref='eHeaderContainer']//div[@col-id='sizetype']//span[@ref='eMenu'])[2]";
	public static String View_Cost = "View_Cost>//button[@id='ERU-ERU_btnHideCostColumns']";
	public static String Loads_cost = "Loads_cost>(//*[text()='Load Cost'])[1]";
	public static String HorizontalScrollElement = "Horizontal Element>//div[@id='ERU-ERU_treeTable1_tbl']//div[@ref='eHorizontalScrollBody']";
	// div[@col-id='dLoadCost']
	public static String HorizontalScrollElement1 = "Horizontal Element>//div[@id='ERU-ERU_treeTable1_tbl']//div[@ref='eBodyHorizontalScrollViewport']";

	public static String Search_Input = "Search Input>//input[@id='nfr_topbar_autocomp_input']";
	public static String Ero_value = "Ero_value>//span[text()='ERO Load Cost']";
	public static String Gloal_search = "Gloal_search>//button[@id='ELO-ELO_Toolbarid-btnTblJdlgSearch']";
	public static String Location_Search = "Location_Search>//input[@id='txt_name1']";
	public static String Equipment_Type = "Equipment_Type>//input[@id='txt_name3']";
	public static String Search_OK_button = "Search Ok button>//button[@id='myBtn']";
	public static String last_Option = "last_Option>(//div[@col-id='C1'])";
	public static String select_val = "select_val>//button[@id='nfr_sch_jdlg_form-jdlg_okbtn']";
	public static String Total_val = "Total_val>//input[@id='ELO-ELO_txtTot_input']";
	public static String Total_Val1 = "Total_Val1>//input[@id='EDI-EDI_txtTot_input']";
	public static String Deficit1option = "Deficit1option>//input[@id='DSL-DSL_txtID']";
     public static String idval="idval>//input[@id='ERU-ERU_txtID']";
	public static String id_ERO = "id_ERO>//input[@id='ERU-ERU_txtID']";
	public static String Ero_cancle = "Ero_cancle>//a[@id='h2_img3']";
	public static String Ero_cancle1 = "Ero_cancle>//a[@id='h4_img3']";
	public static String Ero_cancle2 = "Ero_cancle>//a[@id='h6_img3']";
	public static String Defi_close = "Defi_close>//a[@id='h1_img3']";
	public static String Defic_cancle = "Defic_cancle>//a[@id='h1_img3']";
	public static String Defic_cancle1 = "Defic_cancle>//a[@id='h3_img3']";
	public static String Defic_cancle2 = "Defic_cancle>//a[@id='h5_img3']";
	public static String SVM_Dropdown = "SVM_Dropdown>(//li[@id='ERU-ERU_tree-0']//span)[2]";
	public static String AFR_Dropdown = "AFR_Dropdown>(//li[@id='ERU-ERU_tree-0_0']//span)[2]";
	public static String Ad_option = "Ad_option>(//span[text()='AD'])[1]";
	public static String Ad_Dropdown = "Ad_Dropdown>(//li[@id='ERU-ERU_tree-0_0_0']//span)[2]";
	public static String Adsfc_Option = "Adsfc_Option>//span[text()='ADSFC(OW)']";
	public static String Ar_dropdown = "Ar_dropdown>(//li[@id='ERU-ERU_tree-0_0_1']//span)[2]";
	public static String Arrga_Option = "Arrga_Option>//span[text()='ARRGA(OF)']";
	public static String Optimizer_Clo = "Optimizer_Clo>(//i[@class='fa fa-remove mdlclose'])[3]";
	public static String Opti_first = "Opti_first>((//tr[@data-ri='0'])[1]//td)[1]";
	public static String Opti_first_Header = "Opti_first_Header>(//thead[@id='OPT-OPT_treeTable_head']//th)[1]";
	public static String All_option = "All_option>//input[@id='ERU-ERU_thirdbox']";
	public static String Disable_SizeType = "Disable_SizeType>//input[@id='ERU-ERU_cmbSizetype_focus']";
	public static String All_20s_Option = "All_20s_Option>//input[@id='ERU-ERU_firstbox']";
	public static String All_40s_Option = "All_40s_Option>//input[@id='ERU-ERU_secondtbox']";
	public static String Ero_Discharge_Cost = "Ero_Discharge_Cost>//li[@data-item-label='ERO Discharge Cost']";
	public static String ERO_Global_Search = "ERO_Global_Search>//button[@id='EDI-EDI_Toolbarid-btnTblJdlgSearch']";
	public static String ERO_Haulage_Cost = "ERO_Haulage_Cost>//li[@data-item-label='ERO Haulage Cost']";
	public static String ERO_Global_Haulage = "ERO_Global_Haulage>//button[@id='EHC-EHC_toolbarid-btnTblJdlgSearch']";
	public static String ERO_Global_Haulage1 = "ERO_Global_Haulage>//button[@id='EDI-EDI_Toolbarid-btnTblJdlgSearch']";

	public static String ERO_Haulage_Total = "ERO_Haulage_Total>//input[@id='EHC-EHC_txtTot_input']";
	public static String ERO_Transhipment = "ERO_Transhipment>//li[@data-item-label='ERO Transhipment Cost']";
	public static String ERO_Type = "ERO_Type>//label[@id='OTC-OTC_cmbType_label']";
	public static String ERO_Load_Transhipment = "ERO_Load_Transhipment>//li[@id='OTC-OTC_cmbType_1']";
	public static String ERO_Transhipment_GlobalSearch = "ERO_Transhipment_GlobalSearch>//button[@id='OTC-OTC_toolbarid-btnTblJdlgSearch']";
	public static String ERO_Transhipment_Total = "ERO_Transhipment_Total>//input[@id='OTC-OTC_txtTot_input']";
	public static String ERO_External_Feeder_Cost = "ERO_External_Feeder_Cost>//li[@data-item-label='ERO External Feeder Cost']";
	public static String ERO_External_Feeder_Cost_GlobalSearch = "ERO_External_Feeder_Cost_GlobalSearch>//button[@id='EXF-EXF_Toolbarid-btnTblJdlgSearch']";
	public static String ERO_External_Feeder_Cost_Total = "ERO_External_Feeder_Cost_Total>//input[@id='EXF-EXF_txtTot_input']";
	public static String ERO_Equipment_Reposition_Report = "ERO_Equipment_Reposition_Report>//a[text()='Equipment Reposition Report']";
	public static String ERO_Equipment_Reposition_Repor2t = "ERO_Equipment_Reposition_Report>(//a[text()='Equipment Reposition Report'])[2]";
	public static String ERO_Equipment_Reposition_Repor1t = "ERO_Equipment_Reposition_Report>(//a[text()='Equipment Reposition Report'])[1]";
	public static String ERO_Load_Location = "ERO_Load_Location>(//*[text()='Load Location'])[3]";
	public static String ERo_SizeType_drop = "ERo_SizeType_drop>(//span[@class='ag-header-icon ag-header-cell-menu-button'])[15]";
	public static String ERO_Size_Type_first = "ERO_Size_Type_first>(//span[@ref='eFilterItemValue'])[1]";
	public static String ERO_Size_Type_second = "ERO_Size_Type_second>(//span[@ref='eFilterItemValue'])[2]";
	public static String ERO_Size_Type_3 = "ERO_Size_Type_3>(//span[@ref='eFilterItemValue'])[3]";
	public static String ERO_Optimizer_Close = "ERO_Optimizer_Close>//a[@id='h4_img3']";
	public static String ERO_Optimizer_Close8 = "ERO_Optimizer_Close>//a[@id='h8_img3']";
	public static String ERO_Optimizer_Close1 = "ERO_Optimizer_Close>//a[@id='h5_img3']";
	public static String ERO_20HC = "ERO_20HC>(//a[text()='20HC'])[1]";
	public static String ERO_20HH = "ERO_20HH>(//a[text()='20HH'])[1]";
	public static String ERO_Optimizer_Close2 = "ERO_Optimizer_Close>//a[@id='h6_img3']";
	public static String ERO_Size_Type_4 = "ERO_Size_Type_4>(//span[@ref='eFilterItemValue'])[4]";
	public static String ERO_20RF = "ERO_20RF>(//a[text()='20RF'])[1]";
	public static String ERO_Optimizer_Close3 = "ERO_Optimizer_Close>//a[@id='h7_img3']";
	public static String ERO_Size_Type_5 = "ERO_Size_Type_5>(//span[@ref='eFilterItemValue'])[5]";
	public static String ERO_40DY = "ERO_40DY>(//a[text()='40DY'])[1]";
	public static String ERO_Optimizer_Close4 = "ERO_Optimizer_Close>//a[@id='h8_img3']";
	public static String ERO_Size_Type_6 = "ERO_Size_Type_6>(//span[@ref='eFilterItemValue'])[6]";
	public static String ERO_40HC = "ERO_40HC>(//a[text()='40HC'])[1]";
	public static String ERO_Optimizer_Close5 = "ERO_Optimizer_Close>//a[@id='h2_img3']";
	public static String ERO_Size_Type_7 = "ERO_Size_Type_7>(//span[@ref='eFilterItemValue'])[7]";
	public static String ERO_40HR = "ERO_40HR>(//a[text()='40HR'])[1]";
	public static String ERO_Optimizer_Close6 = "ERO_Optimizer_Close>//a[@id='h4_img3']";
	public static String ERO_Size_Type_8 = "ERO_Size_Type_8>//span[text()='40OT']";
	public static String ERO_40OT = "ERO_40OT>(//a[text()='40OT'])[1]";
	public static String ERO_location = "ERO_location>(//th[@role='columnheader']//span[text()='Location'])[2]";
	public static String ERO_Count = "ERO_Count>(//th[@role='columnheader']//span[text()='Count'])[2]";
	public static String ERO_Unsatisfied_Report = "ERO_Unsatisfied_Report>//a[text()='Unsatisfied Report']";
	public static String ERO_Hire_Report = "ERO_Hire_Report>//a[text()='Hire Report']";
	public static String ERO_Lease_Report = "ERO_Lease_Report>//a[text()='Lease Report']";
	public static String ERO_Total_Summary = "ERO_Total_Summary>//a[text()='Total Summary']";
	public static String ERO_One_Way = "ERO_One_Way>//td[text()='One-Way Lease Details']";
	public static String ERO_One_Way_Lease = "ERO_One_Way_Lease>//td[text()='One-Way Lease']";
	public static String ERO_Total_One_Way_Lease = "ERO_Total_One_Way_Lease>//td[text()='Total One-Way Lease']";
	public static String ERO_Summary_Details = "ERO_Summary_Details>//td[text()='Summary Details']";
	public static String ERO_Total_Reposition = "ERO_Total_Reposition>//td[text()='Total Reposition']";
	public static String ERO_Total_lease = "ERO_Total_lease>//td[text()='Total One-Way Lease']";
	public static String ERO_Size_Type_Label = "ERO_Size_Type_Label>//label[@id='ERU-ERU_cmbSizetype_label']";
	public static String ERO_Size_Type_Label_1 = "ERO_Size_Type_Label_1>//li[@id='ERU-ERU_cmbSizetype_1']";
	public static String ERO_Unavailable_Load_Region = "ERO_Unavailable_Load_Region>(//span[text()='Load Region'])[1]";
	public static String ERO_Unavailable_Load_Country = "ERO_Unavailable_Load_Country>(//span[text()='Load Country'])[1]";
	public static String ERO_Unavailable_Load_Origin = "ERO_Unavailable_Load_Country>(//span[text()='Origin'])[3]";
	public static String ERO_Unavailable_Load_Delivery = "ERO_Unavailable_Load_Delivery>(//span[text()='Delivery'])[3]";
	public static String ERO_Unavailable_Load_Disch = "ERO_Unavailable_Load_Disch>(//span[text()='Disch Country'])[1]";
	public static String ERO_Unavailable_Load_Disch_Region = "ERO_Unavailable_Load_Disch_Region>(//span[text()='Disch Region'])[1]";
	public static String Load_cost_vi = "Load_cost_vi>(//div[@col-id='cost' and @role='gridcell'])[1]";
	public static String ERO_Deficit_Val = "ERO_Deficit_Val>//label[@id='OPT-OPT_treeTable3_records_lbl_cnt']";
	public static String ERO_Surplus_Color = "ERO_Surplus_Color>(//td[@class='sm-bg-aqua '])[1]";
	public static String ERO_FJLTK = "ERO_FJLTK>//td[contains(text(),'FJLTK')]";
	public static String ERO_20 = "ERO_20dy>//td[contains(text(),'20DY')][1]";
	public static String filter_main = "filter_main>//div[@id='DSL-DSL_treeTable1_nfr_toolpanel_li_id']";
	public static String Deficit_Condition_Filter = "Deficit_Condition_Filter>(//span[text()='Condition Filter'])[1]";
	public static String Deficit_Location_Field = "Deficit_Location>//div[@aria-colindex='1']//input";
	public static String Deficit_Equipment_Type = "Deficit_Equipment_Type>//input[@aria-label='Equipment Type Filter Input']";
	public static String Defict_surplus = "Defict_surplus>(//div[@col-id='defsurstatusflag'])[2]";
	public static String Dedicit_val = "Dedicit_val>(//td[@class='sm-bg-yellow '])[1]";
	public static String Defict_val = "Defict_surplus>(//div[@col-id='defsurstatusflag'])[2]";
	public static String ERO_AUSYD="ERO_AUSYD>//tbody[@id='OPT-OPT_treeTable_data']//following::td[contains(text(),'AUSYD')]";
	public static String Select_VaL = "Select_VaL>(//div[@ref='eHeaderContainer']//div[@col-id='nfr_sel_col']//span[@ref='eMenu'])[1]";
	public static String Select_VaL1 = "Select_VaL>//span[text()='(Blanks)']";
	public static String Route_Origin = "Route_Origin>(//div[@ref='eHeaderContainer']//div[@col-id='origin']//span[@ref='eMenu'])[1]";
	public static String Route_Delivery = "Route_Delivery>(//div[@ref='eHeaderContainer']//div[@col-id='delivery']//span[@ref='eMenu'])[1]";
	public static String Route_Size_Type = "Route_Size_Type>(//div[@ref='eHeaderContainer']//div[@col-id='sizetype']//span[@ref='eMenu'])[1]";
	public static String Route_Cost = "Route_Cost>(//div[@ref='eHeaderContainer']//div[@col-id='cost']//span[@ref='eMenu'])[1]";
	public static String Route_Main_Service = "Route_Main_Service>(//div[@ref='eHeaderContainer']//div[@col-id='mainservice']//span[@ref='eMenu'])[1]";
	public static String Route_Origin_Mode = "Route_Origin_Mode>(//div[@ref='eHeaderContainer']//div[@col-id='sOrgMode']//span[@ref='eMenu'])[1]";
	public static String Route_Pol = "Route_Pol>(//div[@ref='eHeaderContainer']//div[@col-id='pOL']//span[@ref='eMenu'])[1]";
	public static String Route_Pol_Terminal = "Route_Pol_Terminal>(//div[@ref='eHeaderContainer']//div[@col-id='pOLter']//span[@ref='eMenu'])[1]";
	public static String Route_Pol_Service = "Route_Pol_Service>(//div[@ref='eHeaderContainer']//div[@col-id='pOLservice']//span[@ref='eMenu'])[1]";
	public static String Route_Trans1 = "Route_Trans1>(//div[@ref='eHeaderContainer']//div[@col-id='trans1']//span[@ref='eMenu'])[1]";
	public static String Route_Trans1_Service = "Route_Trans1_SErvice>(//div[@ref='eHeaderContainer']//div[@col-id='trans1ser']//span[@ref='eMenu'])[1]";
	public static String Route_Trans2 = "Route_Trans2>(//div[@ref='eHeaderContainer']//div[@col-id='trans2']//span[@ref='eMenu'])[1]";
	public static String Route_Trans2_Service = "Route_Trans2_SErvice>(//div[@ref='eHeaderContainer']//div[@col-id='trans2ser']//span[@ref='eMenu'])[1]";
	public static String Route_Trans3 = "Route_Trans3>(//div[@ref='eHeaderContainer']//div[@col-id='trans3']//span[@ref='eMenu'])[1]";
	public static String Route_Trans3_Service = "Route_Trans3_Service>(//div[@ref='eHeaderContainer']//div[@col-id='trans3ser']//span[@ref='eMenu'])[1]";
	public static String Route_Pod = "Route_Pod>(//div[@ref='eHeaderContainer']//div[@col-id='pOD']//span[@ref='eMenu'])[1]";
	public static String Route_Pod_Terminal = "Route_Pod_Terminal>(//div[@ref='eHeaderContainer']//div[@col-id='pODter']//span[@ref='eMenu'])[1]";
	public static String Route_Delivery_mode = "Route_Delivery_mode>(//div[@ref='eHeaderContainer']//div[@col-id='sDelMode']//span[@ref='eMenu'])[1]";
	public static String Route_Transit_Day = "Route_Transit_Day>(//div[@ref='eHeaderContainer']//div[@col-id='transittime']//span[@ref='eMenu'])[1]";
	public static String Route_Missing_Cost = "Route_Missing_Cost>(//div[@ref='eHeaderContainer']//div[@col-id='missingcost']//span[@ref='eMenu'])[1]";
	public static String Route_Routing = "Route_Routing>(//div[@ref='eHeaderContainer']//div[@col-id='sRoutingFrom']//span[@ref='eMenu'])[1]";
	public static String Route_Origin_Val = "Route_Origin_Val>(//span[text()='AEJEA(OW)'])[2]";
	public static String Route_Delivery_val = "Route_Origin_Val>(//span[text()='AEJEA'])[3]";
	public static String Route_SizrType_val = "Route_Origin_Val>(//span[text()='20DY'])[1]";
	public static String Route_Cost_val = "Route_Cost_val>(//span[text()='1002.38'])[1]";
	public static String Route_Main_Service_val = "Route_Origin_Val>(//span[text()='(Blanks)'])[1]";
	public static String Route_Origin_Mode_val = "Route_Origin_Mode_val>(//span[text()='R'])[1]";
	public static String Route_Pol_val = "Route_Pol_val>(//span[text()='ASPPG'])[3]";
	public static String Route_Pol_Terminal_val = "Route_Pol_Terminal_val>(//span[text()='AEJEATERM'])[1]";
	public static String Route_First_Val = "Route_Pol_Terminal_val>(//div[@role='presentation' and @ref='eWrapper']//following::span[@ref='eFilterItemValue'])[1]";
	public static String Pop_Size = "Pop_Size>//span[text()='Select the Size Type']";
	public static String Pop_Size_Ok = "Pop_Size_Ok>//button[text()='Ok']";
	public static String Optimizer_Pop = "Optimizer_Pop>//span[@id='ERU_Ref_title']";
	public static String ERO_Chat = "ERO_Chat>//a[text()='ERO Chart']";
	public static String ERO_Hire_Summary = "ERO_Chat>//a[text()='On/Off-Hire Summary']";
	public static String ERO_20Hc_Val = "ERO_20Hc_Val>//li[@id='ERU-ERU_cmbSizetype_2']";
	public static String ERO_20_HH_Val = "ERO_20_HH_Val>//li[@id='ERU-ERU_cmbSizetype_3']";
	public static String ERO_20RF_Val = "ERO_20RF_Val>//li[@id='ERU-ERU_cmbSizetype_4']";
	public static String Defi_From_Dropdown = "Defi_From_Dropdown>((//span[@id='DSL-DSL_spnFromYear']//a)[2]//span)[2]";
	public static String Defi_To_Dropdown = "Defi_To_Dropdown>((//span[@id='DSL-DSL_spnToYear']//a)[2]//span)[2]";
	public static String Defi_To_Week = "Defi_To_Week>//input[@id='DSL-DSL_txtToWeek_input']";
	public static String Show_Val = "Show>//button[@id='DSL-DSL_btnShow']";
	public static String No_Record_Pop = "No_Record_Pop>//span[text()='No Records']";
	public static String Ok_Pop = "Optimizer>(//span[text()='OK'])[1]";
	public static String Defi_Status = "Defi_Status>(//div[@id='DSL-DSL_treeTable1']//following::span[@ref='eMenu'])[2]";
	public static String Defi_Status_surplus = "Defi_Status_surplus>(//div[@role='presentation' and @ref='eCheckbox'])[2]";
	public static String Defi_Status_surplus1 = "Defi_Status_surplus>//*[text()='Surplus']";
	public static String Deficit_Total = "Deficit_Total>//label[@id='DSL-DSL_treeTable1_records_lbl_cnt']";
	public static String Surplus_Color = "Surplus_Color>(//tr[@role='row' and @data-ri='1']/td[@role='gridcell'])[2]";
	public static String Deficit_Val = "Deficit_Val>//*[text()='Deficit']";
	public static String deficit_color = "deficit_color>(//tr[@data-ri='0']/td)[2]";
	public static String Deficit_Location = "Deficit_Location>(//span[@ref='eMenu'])[1]";
	public static String Defi_Search = "Defi_Search>(//input[@ref='eInput' and @placeholder='Search...'])[2]";
	public static String Surplus_Total = "Surplus_Total>//label[@id='OPT-OPT_treeTable2_records_lbl_cnt']";
	public static String Optimizer_LoadLocation = "Optimizer_LoadLocation>(//span[text()='Load Location' and @role='columnheader'])[1]";
	public static String Optimizer_DischLocation = "Optimizer_DischLocation>(//span[text()='Disch Location' and @role='columnheader'])[1]";
	public static String Optimizer_EquipmentType = "Optimizer_EquipmentType>(//span[text()='Equipment Type' and @role='columnheader'])[2]";
	public static String Optimizer_Quantity = "Optimizer_Quantity>(//span[text()='Quantity' and @role='columnheader'])[1]";
	public static String Optimizer_CostPerBox = "Optimizer_Quantity>(//span[text()='Cost Per Box(USD)' and @role='columnheader'])[1]";
	public static String Deficit_blue = "Deficit_blue>(//td[@class='sm-bg-aqua '])[1]";
	public static String Optimizer_First_val = "Optimizer_First_val>(//label[@class='ag-set-filter-item'])[1]";
	public static String Optimizer_Location_Filter = "Optimizer_Location_Filter>(//span[@ref='eMenu'])[1]";
	public static String Optimizer_DitchLocation_Filter = "Optimizer_DitchLocation_Filter>(//span[@ref='eMenu'])[2]";
	public static String Optimizer_Equipment_Type_Filter = "Optimizer_Equipment_Type_Filter>(//span[@ref='eMenu'])[3]";
	public static String Optimizer_Quantity_Filter = "Optimizer_Quantity_Filter>(//span[@ref='eMenu'])[4]";
	public static String Optimizer_Cost_per_Box_Filter = "Optimizer_Cost_per_Box_Filter>(//span[@ref='eMenu'])[5]";
	public static String Optimizer_Total_CostFilter = "Optimizer_Total_CostFilter>(//span[@ref='eMenu'])[6]";
	public static String Optimizer_Transit_Days_CostFilter = "Optimizer_Transit_Days_CostFilter>(//span[@ref='eMenu'])[7]";
	public static String Optimizer_RemarksFilter = "Optimizer_Transit_Days_CostFilter>(//span[@ref='eMenu']/span)[3]";
	public static String Optimizer_Load_RegionFilter = "Optimizer_Load_RegionFilter>(//span[@ref='eMenu']/span)[4]";
	public static String Optimizer_Load_Country_Filter = "Optimizer_Load_Country_Filter>(//span[@ref='eMenu']/span)[5]";
	public static String Optimizer_Ditch_Country_Filter = "Optimizer_Load_Country_Filter>(//span[@ref='eMenu']/span)[6]";
    public static String  Optimizer_Main_Service_Filter="Optimizer_Main_Service_Filter>(//span[@ref='eMenu']/span)[8]";
    public static String Optimizer_Quantity1="Optimizer_Quantity>(//div[@col-id='containercount'])[2]";
	public static String Optimizer_Cost_Per="Optimizer_Cost_Per>//div[@row-id='0']//div[@role='gridcell' and @col-id='containercount']";
	public static String Optimizer_Total_Cost="Optimizer_Total_Cost>//div[@row-id='0']//div[@role='gridcell' and @col-id='totcost']";
	public static String Optimizer_pol="Optimizer_pol>//div[@col-id='pOL']//following::span";
	public static String Optimizer_Pol_Service="Optimizer_Pol_Service>//div[@col-id='pOLService']//following::span";
	public static String Optimizer_trans1="Optimizer_trans1>//div[@col-id='trans1']//following::span";
	public static String Optimizer_trans1Svc="Optimizer_trans1Svc>//div[@col-id='trans1Svc']//following::span";
	public static String Optimizer_trans2="trans2>//div[@col-id='trans2']//following::span";
	public static String Optimizer_trans2Svc="Optimizer_trans2Svc>//div[@col-id='trans2Svc']//following::span";
	public static String Optimizer_trans3="Optimizer_trans3>//div[@col-id='trans3']//following::span";
	public static String Optimizer_trans3Svc="Optimizer_trans3Svc>(//div[@col-id='trans3Svc']//following::span)[1]";
	public static String Optimizer_Pod="Optimizer_pod>//div[@col-id='pOD']//following::span";
	public static String Optimizer_delivery_mode="Optimizer_delivery_mode>//div[@col-id='dischmmrsector']//following::span";
	public static String Optimizer_LoadCost="Optimizer_LoadCost>//div[@col-id='dLoadCost']//following::span";
	public static String Optimizer_DischDCost="Optimizer_DischDCost>//div[@col-id='dDischDCost']//following::span";
	public static String Optimizer_TS1LoadCost="Optimizer_DischDCost>//div[@col-id='dTS1LoadCost']//following::span";
	public static String Optimizer_TS2LoadCost="Optimizer_DischDCost>//div[@col-id='dTS2LoadCost']//following::span";
	public static String Optimizer_TS3LoadCost="Optimizer_TS3LoadCost>//div[@col-id='dTS3LoadCost']//following::span";
	public static String Optimizer_DTS1DischCost="Optimizer_TS1DischCost>//div[@col-id='dTS1DischCost']//following::span";
	public static String Optimizer_TS2DischCost="Optimizer_TS2DischCost>//div[@col-id='dTS2DischCost']//following::span";
	public static String Optimizer_TS3DischCost="Optimizer_TS3DischCost>//div[@col-id='dTS3DischCost']//following::span";
	public static String Optimizer_FeederCost="Optimizer_FeederCost>//div[@col-id='dFdrCost1']//following::span";
	public static String Optimizer_Feeder1terms="Optimizer_Feeder1terms>//div[@col-id='loadsector']//following::span";
	public static String Optimizer_FeederCost2="Optimizer_FeederCost2>//div[@col-id='dFdrCost2']//following::span";
	public static String Optimizer_Feeder2terms="Optimizer_Feeder2terms>//div[@col-id='dischsector']//following::span";
	public static String Optimizer_FeederCost3="Optimizer_FeederCost3>//div[@col-id='dFdrCost3']//following::span";
	public static String Optimizer_Feeder3terms="Optimizer_Feeder3terms>//div[@col-id='loadtca']//following::span";
	public static String Optimizer_LoadHlgCost="Optimizer_LoadHlgCost>//div[@col-id='dLoadHlgCost']//following::span";
	public static String Optimizer_DischHlgCost="Optimizer_DischDCost>//div[@col-id='dDischHlgCost']//following::span";
	public static String Optimizer_DPH_Origin_Cost="Optimizer_DPH_Origin_Cost>//div[@col-id='dIntFdrCost1']//following::span";
	public static String Optimizer_Destination_Cost="Optimizer_Destination_Cost>//div[@col-id='dIntFdrCost2']//following::span";
	public static String Optimizer_LTC_Origin_Cost="Optimizer_LTC_Origin_Cost>//div[@col-id='dIntFdrCost3']//following::span";
	public static String Optimizer_LTC_Destination_Cost="Optimizer_LTC_Destination_Cost>//div[@col-id='dIntFdrCost4']//following::span";
	public static String Optimizer_In_Service_Destination_Cost="Optimizer_In_Service_Destination_Cost>//div[@col-id='dOthersCost']//following::span";
	public static String Optimizer_Equipment_Reposition_Report="Optimizer_Equipment_Reposition_Report>//div[@id='OPT-OPT_treeTable1_nfr_toolpanel_li_id']";
	public static String Optimizer_Equipment_Reposition_Report_Filter="Optimizer_Equipment_Reposition_Report_Filter>(//input[@ref='eInput'])[9]";
	public static String OPtimizer_Condition_Filter="OPtimizer_Condition_Filter>(//span[text()='Distinct Filter'])[1]";
	public static String Optimizer_filter_Option=">(//span[@role='treeitem'])[2]";
	public static String Optimizer_total="Optimizer_total>//label[@id='OPT-OPT_treeTable1_records_lbl_cnt']";
	
	public static String Click_popupOk="Click_popupOk>//button[@id='DSL_btnYes']";
	public static String Un_region1="Un_region1>(//div[@col-id='sLoadregion'])[2]";
	
	public static String Select_checkbox1="Select_checkbox1>(//div[@col-id='nfr_sel_col']//input[@type='checkbox'])[2]";
	public static String Haulage_color="Haulage_color>//div[text()='AUSYD(OW)']";
	
	public static String optimizer_png_dropdown="optimizer_png_dropdown>(//span[@class='ui-tree-toggler ui-icon ui-icon-triangle-1-e'])[1]";
	public static String Optimizer_pg_Dropdown="Optimizer_pg_Dropdown>(//span[@class='ui-tree-toggler ui-icon ui-icon-triangle-1-e'])[1]";
	public static String optimizer_pggur="optimizer_pggur>(//span[text()='PGGUR'])[1]";
	public static String Pg_Option="Pg_Option>(//span[text()='PG'])[1]";
	public static String svm_close_drop="svm_close_drop>(//span[@class='ui-tree-toggler ui-icon ui-icon-triangle-1-s'])[1]";
	public static String Pg_close_dropdown="Pg_close_dropdown>(//span[@class='ui-tree-toggler ui-icon ui-icon-triangle-1-s'])[3]";
	public static String png_close_dropdown="png_close_dropdown>(//span[@class='ui-tree-toggler ui-icon ui-icon-triangle-1-s'])[2]";
	public static String Total_Quantity="Total_Quantity>//input[@id='OPT-OPT_txttotalqty2']";
	public static String AverageCost="AverageCost>//input[@id='OPT-OPT_txttotalCost2_input']";
	public static String Grand_Total="Grand_Total>//input[@id='OPT-OPT_txtGrandTotal2_input']";
	public static String scroll_val="scroll_val>//div[@row-id='1']//div[@col-id='containercount']";
	public static String scoll="scoll>(//div[@col-id='totcost'])[2]";
	public static String ERo_origin_filter="ERo_origin_filter>(//span[@ref='eMenu'])[13]";
	public static String ero_Delivery="ero_Delivery>//div[@col-id='delivery']//following::span";
	public static String ero_sizetype="ero_sizetype>//div[@col-id='sizetype']//following::span";
	public static String ero_cost="ero_cost>//div[@col-id='cost']//following::span";
	public static String Main_service="Main_service>//div[@col-id='mainservice']//following::span";
	public static String Origin_cost="Origin_cost>//div[@col-id='sOrgMode']//following::span";
	public static String Pol_ero="Pol_ero>//div[@col-id='pOL']//following::span";
	public static String Pol_terminal="Pol_terminal>//div[@col-id='pOLter']//following::span";
	public static String Pol_service="Pol_service>//div[@col-id='pOLservice']//following::span";
	public static String Pol_trans1="Pol_trans1>//div[@col-id='trans1']//following::span";
	public static String Pol_trans1Service="Pol_trans1Service>//div[@col-id='trans1ser']//following::span";
	public static String Pol_trans2="Pol_trans2>//div[@col-id='trans2']//following::span";
	public static String Pol_trans2Service="Pol_trans2Service>//div[@col-id='trans2ser']//following::span";
	public static String Pol_trans3="Pol_trans2>//div[@col-id='trans3']//following::span";
	public static String Pol_trans3Service="Pol_trans3Service>//div[@col-id='trans3ser']//following::span";
	public static String Pod="Pod>//div[@col-id='pOD']//following::span";
	public static String Pod_terminal="Pod_terminal>//div[@col-id='pODter']//following::span";
	public static String Pod_Delivery_mode="Pod_Delivery_mode>//div[@col-id='sDelMode']//following::span";
	public static String Pod_Transit="Pod_Transit>//div[@col-id='transittime']//following::span";
	public static String Pod_missingcost="Pod_missingcost>//div[@col-id='missingcost']//following::span";
	public static String Pod_routing="Pod_routing>//div[@col-id='sRoutingFrom']//following::span";
	public static String Condition_fil="Condition_fil>(//span[text()='Condition Filter'])[2]";
	public static String Origin_fil="Origin_fil>//div[@row-id='0']//div[@role='gridcell' and @col-id='origin']";
	public static String Origin_Delivery="Origin_Delivery>//div[@row-id='0']//div[@role='gridcell' and @col-id='delivery']";
	public static String Origin_Size_type="Origin_Size_type>//div[@row-id='0']//div[@role='gridcell' and @col-id='sizetype']";
	public static String Origin_Cost="Origin_Cost>//div[@row-id='0']//div[@role='gridcell' and @col-id='cost']";
	public static String Origin_main_service="Origin_main_service>//div[@row-id='0']//div[@role='gridcell' and @col-id='mainservice']";
	public static String Origin_Origin_mode="Origin_Origin_mode>//div[@row-id='0']//div[@role='gridcell' and @col-id='sOrgMode']";
	public static String Origin_Origin_Pol="Origin_Origin_Pol>//div[@row-id='0']//div[@role='gridcell' and @col-id='pOL']";
	public static String Origin_Origin_Pol_terminal="Origin_Origin_Pol_terminal>//div[@row-id='0']//div[@role='gridcell' and @col-id='pOLter']";
	public static String Origin_Origin_Pol_Service="Origin_Origin_Pol_Service>//div[@row-id='0']//div[@role='gridcell' and @col-id='pOLservice']";
	public static String Origin_Trans="Origin_Trans>//div[@row-id='0']//div[@role='gridcell' and @col-id='trans1']";
	public static String Origin_Trans_ser="Origin_Trans>//div[@row-id='0']//div[@role='gridcell' and @col-id='trans1ser']";
	public static String Origin_Trans2="Origin_Trans>//div[@row-id='0']//div[@role='gridcell' and @col-id='trans2']";
	public static String Origin_Trans_ser2="Origin_Trans>//div[@row-id='0']//div[@role='gridcell' and @col-id='trans2ser']";
	public static String Origin_trans3="Origin_trans3>//div[@row-id='0']//div[@role='gridcell' and @col-id='trans3']";
	public static String Origin_trans3ser="Origin_trans3ser>//div[@row-id='0']//div[@role='gridcell' and @col-id='trans3ser']";
	public static String Origin_pOD="Origin_pOD>//div[@row-id='0']//div[@role='gridcell' and @col-id='pOD']";
	
	
	
	public static String Input_origin="Input_origin>//input[@aria-label='Origin Filter Input']";
	public static String Input_Delivery="Input_Delivery>//input[@aria-label='Delivery Filter Input']";
	public static String Input_sizetype="Input_sizetype>//input[@aria-label='Size Type Filter Input']";
	public static String Input_Cost_usd="Input_Cost_usd>//input[@aria-label='Cost (USD) Filter Input']";
	public static String Input_Main_service="Input_Main_service>//input[@aria-label='Main Service Filter Input']";
	public static String Input_Origin_mode="Input_Origin_mode>//input[@aria-label='Origin Mode Filter Input']";
	public static String Input_Pol="Input_Pol>//input[@aria-label='POL Filter Input']";
	public static String Input_Pol_Terminal="Input_Pol_Terminal>//input[@aria-label='POL Terminal Filter Input']";
	public static String Input_Pol_service="Input_Pol_Terminal>//input[@aria-label='POL Service Filter Input']";
	public static String Input_Trans="Input_Trans>//input[@aria-label='Trans1 Filter Input']";
	public static String Input_Trans1Service="Input_Trans1Service>//input[@aria-label='Trans1 Ser Filter Input']";
	public static String Input_Trans2="Input_Trans2>//input[@aria-label='Trans2 Filter Input']";
	public static String Input_Trans2Service="Input_Trans1Service>//input[@aria-label='Trans2 Ser Filter Input']";
	public static String Input_Trans3="Input_Trans3>//input[@aria-label='Trans3 Filter Input']";
	public static String Input_Trans3Service="Input_Trans1Service>//input[@aria-label='Trans3 Ser Filter Input']";
	public static String Input_pod="Input_pod>//input[@aria-label='POD Filter Input']";
	public static String Input_pod_terminal="Input_pod_terminal>//input[@aria-label='POD Terminal Filter Input']";
	public static String Input_Delivery_mode="Input_Delivery_mode>//input[@aria-label='Delivery Mode Filter Input']";
	public static String Input_Transit="Input_Transit>//input[@aria-label='Transit Days Filter Input']";
	public static String Input_Missing_cost="Input_Missing_cost>//input[@aria-label='Missing Cost Filter Input']";
	public static String Input_Routing="Input_Routing>//input[@aria-label='Routing From Filter Input']";
	public static String AFR_dropOPtio="AFR_dropOPtio>(//li[@id='ERU-ERU_tree-0_0']/span/span)[1]";
	public static String view_cost="view_cost>//span[text()='View Cost Split-Up']";
	public static String Ar_d="Ar_d>//li[@id='ERU-ERU_tree-0_0_2']/span/span";
	public static String OK_Val="OK_Val>//button[text()='Ok']";
	public static String New_Va="New_Va>//button[@id='DSL-DSL_toolbar-btnTblNew']";
	public static String New_yes="New_Va>//button[text()='Yes']";
	public static String missing_close="missing_close>(//span[@class='ui-icon ui-icon-closethick'])[7]";
	public static String size_type_input="size_type_input>(//input[@placeholder='Search...'])[5]";
	public static String EROSaveTemplateInput="SaveTemplateInput>//input[@id='ERU-ERU_treeTable1_txtTemplate']";
	public static String ERosave_template_as="save_template_as>//button[@id='ERU-ERU_treeTable1_callSaveAsTemplate_id']";
	public static String ERO_Chart="ERO Chart>//a[text()='ERO Chart']";
	public static String By_Cost="By cost>//html//li[@id='Button__Tabs_Group_name__Tab_2_name']";	
	public static String By_Region="By_Region>//li[@id='Button__Tabs_Group_name__Tab_3_name']";
	public static String Network_Chart="Network_Chart>//li[@id='Button__Tabs_Group_name__Tab_4_name']";
	public static String Count="Count>//div[@class='amcharts-balloon-div']";
	public static String Emp_Repo="Emp_Repo>//a[text()='Equipment Reposition Solve']";
	public static String Fetch_Value1="Fetch_Value1>(//td[contains(text(),'AUSYD(OW)')]//following::td[@role='gridcell'])[7]";
	public static String Fetch_Value_Deficit="Fetch_Value_Deficit>(//td[contains(text(),'FJLTK')]//following::td[@role='gridcell'])[5]";
	public static String Details1="Details1>(//div[@id='dvolume']//*[name()='path' and @class='amcharts-graph-column-front amcharts-graph-column-element'])[5]";
	public static String Default_Filter="Default_Filter>(//select[@id='region']/option)[1]";
	public static String Details="Details>//div[@id='svolume']//*[name()='path' and @class='amcharts-graph-column-front amcharts-graph-column-element']";
	public static String Surplus_ports="Surplus_ports>(//*[@class='amcharts-axis-label'])[1]";
	public static String Deficit_Port="Deficit_Port>(//div[@id='dvolume']//following::*[@class='amcharts-axis-label'])[1]";
	public static String Region_Dropdown="Region_Dropdown>//select[@id='region']";
	public static String Select_Optimizer="Select_Optimizer>//li[@data-item-label='ERO Routing']";
	public static String By_Volume="By_Volume>//li[@id='Button__Tabs_Group_name__Tab_1_name']";
	public static String Optimizer_Button="Optimizer_Button>//button[@id='ERU-ERU_btnOptimizer']";
	public static String Table="Table>//div[@id='OPT-OPT_pnlChart2']";
	public static String Text1="Text1>//li[text()='By VOLUME']";
	public static String ByCOst="ByCOst>//li[@id='Button__Tabs_Group_name__Tab_2_name']";
	public static String Grid1="Grid1>(//a[text()='20DY'])[2]";
	public static String Close_Optimize="Close_Optimize>(//i[@class='fa fa-remove mdlclose'])[2]";
	public static String ANZ_PieChart="ANZ_PieChart>(//div[@id='chart2']//*[name()='path' and @class='amcharts-pie-slice'])[2]";
	public static String SPI_PieChart="SPI_PieChart>(//div[@id='chart2']//*[name()='path' and @class='amcharts-pie-slice'])[3]";
	public static String PNG_PieChart="PNG_PieChart>(//div[@id='chart2']//*[name()='path' and @class='amcharts-pie-slice'])[4]";
	public static String PNG_PieChart_Color="PNG_PieChart_Color>(//div[@id='chart2']//*[name()='path' and @fill-opacity='1' and @fill='#555555'])[1]";
	public static String SPI_PieChart_Color="SPI_PieChart_Color>(//div[@id='chart2']//*[name()='path' and @fill-opacity='1' and @fill='#5e0707'])[1]";
	public static String ANZ_PieChart_Color="ANZ_PieChart_Color>(//div[@id='chart2']//*[name()='path' and @fill-opacity='1' and @fill='#b25200'])[1]";
	public static String Network_Orgin_Wise="Network_Orgin_Wise>(//select[@id='origin']/option)[1]";
	public static String Network_Orgin_Wise_Dropdown="Network_Orgin_Wise_Dropdown>//select[@id='origin']";
	public static String Deficit_Port1="Deficit_Port1>(//div[@id='dcost']//following::*[@class='amcharts-axis-label'])[1]";
	public static String Surplus_Graph_xAxis="Surplus_Graph_xAxis>(//*[@class='amcharts-axis-title'])[3]";
	public static String Region_Fetch_Graph="Region_Fetch_Graph>(//div[@id='chart4']//*[name()='path' and @class='amcharts-graph-fill'])[2]";
	public static String Fetch_Graph="Fetch_Graph>//div[contains(@class,'amcharts-balloon-div')]";
	public static String Fetch_Graph_Count_EMP="Fetch_Graph_Count_EMP>(//td[contains(text(),'PGPOM')]//following::td[@role='gridcell'])[1]";
	public static String PNG_Region="PNG_Region>//div[@id='chart4']";
	public static String DY="DY>//div[@id='OPT-OPT_tabChart']";
	public static String Fetch_Graph_ANZ="Fetch_Graph_ANZ>(//div[@id='chart4']//*[name()='circle' and @class='amcharts-graph-bullet'])";
	public static String Fetch_Graph1="Fetch_Graph1>(//div[@id='chart4']//*[name()='path' and @class='amcharts-plot-area'])";
	public static String Fetch_Graph1_ANZ="Fetch_Graph1_ANZ>(//td[contains(text(),'AUSYD(OW)')]//following::td[@role='gridcell'])[1]";
	public static String Fetch_Graph1_PNG="Fetch_Graph1_PNG>(//td[contains(text(),'PGWWK')]//following::td[@role='gridcell'])[1]";
	public static String Vol_Surplus_Backward="Vol_Surplus_Backward>//button[@id='svolume1']";
	public static String Vol_Surplus_Forward="Vol_Surplus_Forward>//button[@id='svolume2']";
	public static String Vol_Deficit_Backward="Vol_Surplus_Backward>//button[@id='dvolume1']";
	public static String Vol_Deficit_Forward="Vol_Deficit_Forward>//button[@id='dvolume2']";
	public static String ero_chart = "chart>//object";
	public static String Vol_Surplus_Backward1 = "Vol_Surplus_Backward1>//button[@id='scost1']";
	public static String Vol_Surplus_Forward1="Vol_Surplus_Forward>//button[@id='scost2']";
	public static String Vol_Deficit_Backward1="Vol_Surplus_Backward>//button[@id='dcost1']";
	public static String Vol_Deficit_Forward1="Vol_Deficit_Forward>//button[@id='dcost2']";
	public static String EMP_Report="EMP_Report>//a[text()='Equipment Reposition Report']";
	//public static String Load_Loc_Filter="Load_Loc_Filter>(//span[@ref='eMenu']//following::span[@class='ag-header-icon ag-header-cell-menu-button'])[24]";
	//public static String Load_Loc_Select_Filter="Load_Loc_Select_Filter>(//div[@ref='eHeader']//following::span[@class='ag-icon ag-icon-filter'])[1]";
	public static String Load_Loc_Selectall="Load_Loc_Selectall>//label[@ref='eSelectAllContainer']";
	//public static String Filter_Search="Filter_Search>(//input[@ref='eInput']//following::input[@class='ag-input-field-input ag-text-field-input'])[5]";
	public static String Qty_1="Qty_1>(//div[text()='PGGUR']//following-sibling::div[@col-id='containercount'])[1]";
	public static String Qty_2="Qty_2>(//div[text()='PGGUR']//following-sibling::div[@col-id='containercount'])[2]";
	public static String Qty_3="Qty_3>(//div[text()='PGGUR']//following-sibling::div[@col-id='containercount'])[3]";
	public static String DEFI_Search="DEFI_Search>//li[@data-item-label='Deficit and Surplus Location Identification']";
	public static String Global_Search="Global_Search>//button[@id='DSL-DSL_toolbar-btnTblJdlgSearch']";
	public static String View_GAte="View_GAte>//button[@id='OPT-OPT_btnViewGate']";
	public static String Searchcode_input_ERO = "Searchcode_input_ERO>//input[@aria-label='Load Region Code Filter Input']";
	public static String Load_Region_ERO="Load_Region_ERO>//button[@id='ORG-ORG_btnLoadRegion']";
	public static String Select_Region="Select_Region>//button[@id='nfr-twocol-select-button']";
	public static String Show_Button_ERO1="Show_Button_ERO1>//button[@id='ORG-ORG_btnShow']";
	public static String Load_Location_ERO="Load_Location_ERO>//button[@id='ORG-ORG_btnAddLoc']";
	public static String Load_Location_Search="Load_Location_Search>//input[@aria-label='Load Location Code Filter Input']";
	public static String Load_Location_Select="Load_Location_Select>//button[@id='multicol_okbtn']";
	public static String Load_Location_Select_1="Load_Location_Select_1>//div[@id='nfr-multi-div']//div[@ref='eCenterViewport']//div[@role='row']";
	public static String Total_Qty="Total_Qty>(//input[contains(@id,'ORG-ORG_dynList')])[1]";
	public static String Click_optim="Click_optim>(//a[@class='nfr-tabmdl-link ui-tabs-anchor'])[3]";
	public static String Fetch_Value_Cost="Fetch_Value_Cost>//div[@id='scost']//*[name()='path' and @class='amcharts-graph-column-front amcharts-graph-column-element']";
	public static String Leese_Tab="Leese_Tab>//a[text()='Lease Report']";
	public static String Leese_Filter="Leese_Filter>(//div[@ref='eHeaderContainer']//div[@col-id='origin']//span[@ref='eMenu'])[4]";
	public static String Leese_Search="Leese_Search>//div[@ref='eMiniFilter']//input[@ref='eInput']";
	public static String Leese_Fetch_Value="Leese_Fetch_Value>(//div[@col-id='totcost'])[2]";
	public static String Leese_Deficit_Fetch_Value="Leese_Deficit_Fetch_Value>(//div[@id='dcost']//*[name()='path' and @class='amcharts-graph-column-front amcharts-graph-column-element'])[1]";
	public static String Size1_Emp="Size1_Emp>(//a[text()='Equipment Reposition Solve']//following::a)[8]";
	public static String Size2_Emp="Size2_Emp>(//div[@id='OPT-OPT_tabSolve']//following::li[@role='tab'])[1]";
	public static String Size3_Emp="Size3_Emp>(//div[@id='OPT-OPT_tabSolve']//following::li[@role='tab'])[2]";
	public static String Size4_Emp="Size4_Emp>(//div[@id='OPT-OPT_tabSolve']//following::li[@role='tab'])[3]";
	public static String Size5_Emp="Size5_Emp>(//div[@id='OPT-OPT_tabSolve']//following::li[@role='tab'])[4]";
	public static String Size6_Emp="Size6_Emp>(//div[@id='OPT-OPT_tabSolve']//following::li[@role='tab'])[5]";
	public static String Size7_Emp="Size7_Emp>(//div[@id='OPT-OPT_tabSolve']//following::li[@role='tab'])[6]";
	public static String Size8_Emp="Size8_Emp>(//div[@id='OPT-OPT_tabSolve']//following::li[@role='tab'])[7]";
	public static String Size1_ERO="Size1_ERO>(//div[@id='OPT-OPT_tabSolve']//following::li[@role='tab'])[8]";
	public static String Size2_ERO="Size1_ERO>(//div[@id='OPT-OPT_tabSolve']//following::li[@role='tab'])[9]";
	public static String Size3_ERO="Size1_ERO>(//div[@id='OPT-OPT_tabSolve']//following::li[@role='tab'])[10]";
	public static String Size4_ERO="Size1_ERO>(//div[@id='OPT-OPT_tabSolve']//following::li[@role='tab'])[11]";
	public static String Size5_ERO="Size1_ERO>(//div[@id='OPT-OPT_tabSolve']//following::li[@role='tab'])[12]";
	public static String Size6_ERO="Size1_ERO>(//div[@id='OPT-OPT_tabSolve']//following::li[@role='tab'])[13]";
	public static String Size7_ERO="Size1_ERO>(//div[@id='OPT-OPT_tabSolve']//following::li[@role='tab'])[14]";
	public static String Size8_ERO="Size1_ERO>(//div[@id='OPT-OPT_tabSolve']//following::li[@role='tab'])[15]";
	public static String Type_Filter="Type_Filter>(//div[@ref='eHeaderContainer']//div[@col-id='sizetype']//span[@ref='eMenu'])[2]";
	public static String Report_Size="Report_Size>//span[@ref='eFilterItemValue']";
	public static String SEA_PieChart_Color="SEA_PieChart_Color>(//div[@id='chart2']//*[name()='path' and @fill-opacity='1' and @fill='#135266'])[1]";
	public static String SEA_PieChart_Color_Picker="SEA_PieChart_Color_Picker>(//div[@id='chart2']//*[name()='g' and @aria-label='SEA'])";
	public static String ANZ_PieChart_Color_Picker="ANZ_PieChart_Color_Picker>(//div[@id='chart2']//*[name()='g' and @aria-label='ANZ'])";
	public static String SPI_PieChart_Color_Picker="SPI_PieChart_Color_Picker>(//div[@id='chart2']//*[name()='g' and @aria-label='SPI'])";
	public static String PNG_PieChart_Color_Picker="PNG_PieChart_Color_Picker>(//div[@id='chart2']//*[name()='g' and @aria-label='PNG'])";
	public static String SPI_Graph="SPI_Graph>(//div[@id='chart2']//*[name()='path' and @class='amcharts-pie-slice'])[2]";
	public static String PNG_Graph="PNG_Graph>(//div[@id='chart2']//*[name()='path' and @class='amcharts-pie-slice'])[3]";
	public static String ANZ_Graph="ANZ_Graph>(//div[@id='chart2']//*[name()='path' and @class='amcharts-pie-slice'])[3]";
	public static String ANZ_Graph1="ANZ_Graph1>(//div[@id='chart2']//*[name()='path' and @class='amcharts-pie-slice'])[2]";
	public static String ANZ_Graph2="ANZ_Graph2>(//div[@id='chart2']//*[name()='path' and @class='amcharts-pie-slice'])[1]";
	public static String Filter_Loc="Filter_Loc>(//div[@ref='eHeaderContainer']//div[@col-id='origin']//span[@ref='eMenu'])[2]";


}
