package locators;

public interface ERO_Optimizer_WHATIF_Locators {

	public static String SelectOptimizer = "SelectOptimizer>//span[contains(text(),'Optimizer WHAT – IF Scenario')]";
	public static String Optimizer_close_tab = "close>(//label[text()='Optimizer WHAT – IF Scenario']/following::a)[3]";
	public static String Optimizer_cancle = "cancle>//button[@id='OWS-OWS_toolbar-btnTblCancel']";
	public static String Optimizer_new = "new>//button[@id='OWS-OWS_toolbar-btnTblNew']";
	public static String Optimizer_createnew_confirm = "createnew_confirm>//h2[text()='Optimizer WHAT – IF Scenario']/following::button[text()='Yes']";
	public static String Optimizer_save = "save>//button[@id='OWS-OWS_toolbar-btnsave']";
	public static String Optimizer_Globalserach = "Globalserach>//button[@id='OWS-OWS_btnDeficitSurplusID-OWS_btnDeficitSurplusID']";
	public static String Optimizer_edit = "edit>//button[@id='OWS-OWS_toolbar-btnTblEdit']";
	public static String Optimizer_Grid_locationfield1 = "Grid record location field1>(//div[@col-id='origin'])[2]";
	public static String Optimizer_IDField = "IDField>//input[@id='OWS-OWS_txtDeficitSurplusID']";
	public static String Optimizer_SurplusQty = "Surplus quantity input field>((//div[@row-id='0'])[2]/div)[1]";
	public static String Optimizer_DeficitQty = "Deficit quantity input field>((//div[@row-id='0'])[2]/div)[3]";
	public static String Optimizer_Tree_table = "Optimizer_Tree_table>//div[@id='OWS-OWS_treeTable_nfr_toolpanel_li_id']";
	public static String current_frame = "current_frame>//label[@id='mdl1_tablbl']";
	public static String Optimizer_Verionfield = "Verion field>//label[contains(text(),'Version :')]";
	public static String Optimizer_button = "Optimizer_button>//span[text()='Optimizer']";
	public static String Optimizer_button_cancle = "Optimizer_button cancle>(//span[@id='OWS_Ref_title']//following::span)[1]";
	public static String first_col = "first_col>(//div[@row-id='0'])[2]//following::div[@col-id='origin']";
	public static String Optimizer_Question_Icon = "Question Icon>(//h2[text()='Optimizer WHAT – IF Scenario']/following::span)[1]";
	public static String Optimizer_createnew_confirm_message = "Created new confirm message>//span[text()=' Do you want to create a new Optimizer WHAT – IF Scenario ?']";
	public static String Optmizer_Location_filter = "Location_filter>//div[@col-id='origin']//span";
	public static String surplus_location = "surplus_location>(//div[@id='OWS-OWS_treeTable_tbl']//span[@ref='eMenu'])[1]";
	public static String OPtimizer_Filter_Location = "OPtimizer_Filter_Location>//span[@aria-label='filter']";
	public static String OPtimizer_location3 = "OPtimizer_location3>(//div[@col-id='origin'])[3]";
	public static String Refresh_result = "Refresh_result>//span[text()='Refresh Result']";
	public static String warning_sym = "warning_sym>//span[contains(@class,'warning')]";
	public static String warning_sym_text = "warning_sym_text>//span[text()='Optimizer Result Refreshed']";
	public static String warning_sym_ok = "warning_sym_ok>//button[text()='Ok']";
	public static String Optimizermain_Tree_table = "Tree_table>//div[@id='OWS-OWS_treeTable_nfr_toolpanel_li_id']";
	public static String Optimizer_Condition_filter = "Condition_filter>//a[@id='OWS-OWS_treeTable_conditionFilter_id']";
	public static String Optimizer_filter_input = "filter_input>//input[@aria-label='Surplus Location Filter Input']";
	public static String Optimizer_Search_input = "Search_input>(//div[@col-id='origin']/following::span[@aria-label='filter']/following::input)[1]";
	public static String Optimizer_Filteroption1 = "Optimizer_Filteroption1>((//div[@id='OWS-OWS_treeTable_tbl']//div[@row-id='0'])[2]/div)[1]";
	public static String Optimizer_Filteroption2 = "Optimizer_Filteroption1>((//div[@id='OWS-OWS_treeTable_tbl']//div[@row-id='64'])[2]/div)[1]";
	public static String Optimizer_filter_menu = "Optimizer_filter_menu>//div[@col-id='origin']/following::span[@aria-label='filter']";
	public static String Optimizer_id_filed = "Optimizer_id_filed>//input[@id='OWS-OWS_txtDeficitSurplusID']";
	public static String OPtimizer_new_confirm_no = "OPtimizer_new_confirm_no>//button[text()='No']";
	public static String Optimizer_Export = "Optimizer_Export>//button[@id='OWS-OWS_toolbar-btnTblDynExport']";
	public static String close_2 = "close_2>(//i[@class='fa fa-remove mdlclose'])[2]";
	public static String close_1 = "close_2>(//i[@class='fa fa-remove mdlclose'])[]";
	public static String Optimizer_Excel_Fi = "Excel_fi>(//span[text()='Excel'])[2]";
	public static String refresh_text = "refresh_text>//div[@class='dialog']//span[2]";
	public static String Optimizer_field = "//span[text()='Optimizer']>//span[text()='Optimizer']";
	public static String Optimizer_surplus_location = "Optimizer_surplus_location>(//span[@ref='eMenu'])[1]";
	public static String Optimizer_surplus_Count = "Optimizer_surplus_Count>(//span[@ref='eMenu'])[2]";
	public static String Optimizer_deficit_location = "Optimizer_deficit_location>(//span[@ref='eMenu'])[3]";
	public static String Optimizer_deficit_Count = "Optimizer_deficit_Count>(//span[@ref='eMenu'])[4]";
	public static String Optimizer_result = "Optimizer_result>(//span[@ref='eMenu'])[5]";
	public static String Optimizer_allocate_container = "Optimizer_allocate_container>(//span[@ref='eMenu'])[6]";
	public static String Optimizer_size_type = "Optimizer_size_type>(//span[@ref='eMenu'])[7]";
	public static String Optimizer_cost_unit = "Optimizer_cost_unit>(//span[@ref='eMenu'])[8]";
	public static String OPtimizer_condition_filter = "OPtimizer_condition_filter>(//span[text()='Condition Filter'])[1]";
	public static String surplus_location_input_Filed = "surplus_location_input_Filed>//input[@aria-label='Surplus Location Filter Input']";
	public static String Optimizer_Distint_filter = "Optimizer_Distint_filter>(//span[text()='Distinct Filter'])[1]";
	public static String Optimizer_Total_record = "Total_record>//label[@id='OWS-OWS_treeTable_records_lbl_cnt']";
	public static String grid_table = "grid_table>//div[@id='OWS-OWS_treeTable_tbl']";
	public static String Optimizer_search = "Optimizer_search>//button[@id='OWS-OWS_toolbar-btnTblJdlgSearch']";
	public static String Optimizer_edit1 = "Optimizer_edit>//button[@id='OWS-OWS_toolbar-btnTblEdit']";
	public static String OPtimizer_delete = "OPtimizer_delete>//button[@id='OWS-OWS_toolbar-btnTblDelete']";
	public static String OPtimizer_saveas = "OPtimizer save as>//button[@id='OWS-OWS_toolbar-btnTblSaveas']";
	public static String OPtimizer_print = "OPtimizer print>//button[@id='OWS-OWS_toolbar-btnTblPrint']";
	public static String OPtimizer_MoveToFirstRecord = "OPtimizer_MoveToFirstRecord>//button[@id='OWS-OWS_toolbar-btnTblFrist']";
	public static String OPtimizer_MoveToPrevious_Record = "MoveToPrevious_Record>//button[@id='OWS-OWS_toolbar-btnTblPrev']";
	public static String OPtimizer_MoveToNexrRecord = "MoveToNexrRecord>//button[@id='OWS-OWS_toolbar-btnTblNext']";
	public static String OPtimizer_MoveToLastRecord = "MoveToLastRecord>//button[@id='OWS-OWS_toolbar-btnTblLast']";
	public static String OPtimizer_Magicsave = "OPtimizer_Magicsave>//button[@id='OWS-OWS_toolbar-btnTblAutosave']";
	public static String OPtimizer_refreshResult = "OPtimizer_refreshResult>//button[@id='OWS-OWS_btnRefreshResult']";
	public static String OPtimizer_all = "OPtimizer_all>//input[@id='OWS-OWS_thirdbox']";
	public static String OPtimizer_20s = "OPtimizer 20s>//input[@id='OWS-OWS_firstbox']";
	public static String OPtimizer_40s = "OPtimizer 40s>//input[@id='OWS-OWS_secondtbox']";
	public static String OPtimizer_sizeStpe = "OPtimizer size type>//label[@id='OWS-OWS_cmbSizetype_label']";
	public static String OPtimizer_all_disabled = "OPtimizer_all>//input[@id='OWS-OWS_thirdbox' and @disabled]";
	public static String OPtimizer_20s_disabled = "OPtimizer 20s>//input[@id='OWS-OWS_firstbox' and @disabled]";
	public static String OPtimizer_40s_disabled = "OPtimizer 40s>//input[@id='OWS-OWS_secondtbox' and @disabled]";
	public static String OPtimizer_sizeStpe_disabled = "OPtimizer size type>//label[@id='OWS-OWS_cmbSizetype_label' and @disabled]";
	public static String OPtimizer_option = "OPtimizer_option>//button[@id='OWS-OWS_btnOptimizer']";
	public static String OPtimizer_SurplusCount = "OPtimizer_SurplusCount>//div[@id='OWS-OWS_treeTable_tbl']//div[@row-id='0']//following::div[@col-id='origincontainers']";
	public static String OPtimizer_Deficit_location = "OPtimizer_Deficit_location>//div[@id='OWS-OWS_treeTable_tbl']//div[@row-id='0']//following::div[@col-id='delivery']";
	public static String OPtimizer_Deficit_Count = "OPtimizer_DeficitCount>//div[@id='OWS-OWS_treeTable_tbl']//div[@row-id='0']//following::div[@col-id='deliverycontainers']";
	public static String OPtimizer_OptimizerResult = "OPtimizer_OptimizerResult>//div[@id='OWS-OWS_treeTable_tbl']//div[@row-id='0']//following::div[@col-id='iAlloc']";
	public static String Optimizer_Allocate_Containers = "Optimizer_Allocate_Containers>((//div[@row-id='0'])[2]//following::div[@col-id='allocatecntr'])[1]";
	public static String Optimizer_Allocate_Containers1 = "Optimizer_Allocate_Containers>((//div[@row-id='0'])[2]//following::div[@col-id='allocatecntr'])[1]/input";
	public static String Optimizer_Size_Type_Val = "SizeType>//div[@id='OWS-OWS_treeTable_tbl']//div[@row-id='0']//following::div[@col-id='sizetype']";
	public static String OPtimizer_units = "OPtimizer_units>//div[@id='OWS-OWS_treeTable_tbl']//div[@row-id='0']//following::div[@col-id='optcost']";
	public static String Optimizer_Reset = "Optimizer_Reset>(//*[text()='Reset'])[1]";
	public static String Optimizer_EquipmentRepositionSolve = "EquipmentRepositionSolve>//a[text()='Equipment Reposition Solve']";
	public static String Optimizer_Ok1 = "Optimizer_Ok>(//span[text()='OK'])[1]";
	public static String SizeType_20dy = "SizeType_20dy>//li[@id='OWS-OWS_cmbSizetype_1']";
	public static String SizeType_20FF = "SizeType_20RF>//li[@id='OWS-OWS_cmbSizetype_2']";
	public static String SizeType_20HB = "SizeType_20HB>//li[@id='OWS-OWS_cmbSizetype_3']";
	public static String SizeType_20HC = "SizeType_20HC>//li[@id='OWS-OWS_cmbSizetype_4']";
	public static String SizeType_20HH = "SizeType_20HH>//li[@id='OWS-OWS_cmbSizetype_5']";
	public static String SizeType_20OT = "SizeType_20dy>//li[@id='OWS-OWS_cmbSizetype_6']";
	public static String SizeType_20RF = "SizeType_20RF>//li[@id='OWS-OWS_cmbSizetype_7']";
	public static String SizeType_20TK = "SizeType_20TK>//li[@id='OWS-OWS_cmbSizetype_8']";
	public static String SizeType_20WW = "SizeType_20WW>//li[@id='OWS-OWS_cmbSizetype_9']";
	public static String SizeType_20DY = "SizeType_20DY>//li[@id='OWS-OWS_cmbSizetype_10']";
	public static String Optimizer_delete_template = "Optimizer delete template>//button[@id='OWS-OWS_treeTable_deleteTemplate_id']";
	public static String Optimizer_save_template = "Optimizer_save_template>//button[@id='OWS-OWS_treeTable_savetemplate_id']";
	public static String Optimizer_save_As_template = "Optimizer_save_As_template>//button[@id='OWS-OWS_treeTable_callSaveAsTemplate_id']";
	public static String Optimizer_save_input = "Optimizer_save_input>//input[@id='OWS-OWS_treeTable_txtTemplate']";
	public static String Optimizer_save_input_save_option = "Optimizer_save_input>//input[@value='Save']";
	public static String Optimizer_delete_template_pop = "Optimizer delete template sucessfully>//p[text()='Template Deleted Successfully']";
	public static String Optimizer_Equipment_Resolve = "Equipment_Resolve>//a[text()='Equipment Reposition Solve']";
	public static String Optimizer_Equipment_Report = "Equipment_Report>//a[text()='Equipment Reposition Report']";
	public static String Optimizer_Unsatisfied_Report = "Unsatisfied Report>//a[text()='Unsatisfied Report']";
	public static String Optimizer_Hire_Report = "Hire Report>//a[text()='Hire Report']";
	public static String Optimizer_Lease_Report = "Lease Report>//a[text()='Lease Report']";
	public static String Optimizer_Ero_Chart = "ERO Chart>//a[text()='ERO Chart']";
	public static String ero_OPtimizer_butt = "ero_OPtimizer_butt>(//span[text()='Optimizer'])[2]";
	public static String ero_OPtimizer_butt_ok = "ero_OPtimizer_butt ok>(//span[text()='OK'])[2]";
	public static String Optimizer_Equipment_Reposition_Resolve_20DY = "Equipment Reposition Resolve>//a[text()='20DY']";
	public static String Optimizer_Equipment_Reposition_Resolve_20HC = "Equipment Reposition Resolve>//div[@id='OPT-OPT_tabSolve']//following::a";
	public static String Optimizer_Equipment_Reposition_Resolve_40HH = "Equipment Reposition Resolve 40H>(//div[@id='OPT-OPT_tabSolve']//following::a)[2]";
	public static String Optimizer_Equipment_Reposition_Resolve_40RF = "Equipment Reposition Resolve 40RF>(//div[@id='OPT-OPT_tabSolve']//following::a)[3]";
	public static String Optimizer_Equipment_Reposition_Resolve_40DY = "Equipment Reposition Resolve 40DY>(//div[@id='OPT-OPT_tabSolve']//following::a)[4]";
	public static String Optimizer_Equipment_Reposition_Resolve_40HC = "Equipment Reposition Resolve 40HC>(//div[@id='OPT-OPT_tabSolve']//following::a)[5]";
	public static String Optimizer_Equipment_Reposition_Resolve_40HR = "Equipment Reposition Resolve 40HR>(//div[@id='OPT-OPT_tabSolve']//following::a)[6]";
	public static String Optimizer_Equipment_Reposition_Resolve_40OT = "Equipment Reposition Resolve 40OT>(//div[@id='OPT-OPT_tabSolve']//following::a)[7]";
	public static String Optimizer_Equipment_container = "Equipment Reposition Resolve 20dy container>//tr[@data-ri='0']/td";
	public static String Optimizer_Page = "Optimizer_Page>(//label[text()='Optimizer WHAT – IF Scenario'])[1]";
	public static String OPtimizer_deficit_colour = "OPtimizer_deficit_colour>//button[@id='OPT-OPT_btnRes2']";
	public static String Optimizer_surplus_color = "Optimizer_surplus_color>//button[@id='OPT-OPT_btnRes1']";
	public static String OPtimizer_Reposition_Allocated = "OPtimizer_Reposition_Allocated>//button[@id='OPT-OPT_btnRes4']";
	public static String OPtimizer_onAndOff = "OPtimizer_Reposition_on andoff>//button[@id='OPT-OPT_btnRes5']";
	public static String OPtimizer_One_Way_Lease = "OPtimizer_Reposition_one way lease>//button[@id='OPT-OPT_btnRes6']";
	public static String Optimizer_surplus_qty = "Optimizer_surplus_qty>//input[@id='OPT-OPT_txtTotalCount']";
	public static String Optimizer_Deficit_qty = "Optimizer_DEficit_qty>//input[@id='OPT-OPT_txtTotalCount1']";
	public static String Optimzer_Aveage_cost = "Optimzer_Aveage_cost>//input[@id='OPT-OPT_txttotalCost_input']";
	public static String Optimzer_Total_cost = "Optimzer_Aveage_cost>//input[@id='OPT-OPT_txttotalqty']";
	public static String optimizer_EquipmentReport = "optimizer_EquipmentReport>//input[@id='OPT-OPT_txttotalqty2']";
	public static String Optimizer_Equipment_GrandTotal = "Optimizer_Equipment_GrandTotal>//input[@id='OPT-OPT_txtGrandTotal2_input']";
	public static String Scroll_val = "Scroll_val>//div[@id='OPT-OPT_treeTable1_tbl']//div[@ref='eBodyViewport']";
	public static String Optimizer_LocationCode = "Optimizer_LocationCode>//span[text()='Location Code']";
	public static String Optimizer_EquipmentType1 = "Optimizer_EquipmentType>(//span[text()='Equipment Type'])[3]";
	public static String Optimizer_Quantity1v = "Optimizer_Quantity>(//span[text()='Quantity'])[3]";
	public static String Optimizer_Remarks_va = "Optimizer_Remarks>(//span[text()='Remarks'])[3]";
	public static String Exel_2007 = "Download the excel>//a[@id='OWS-OWS_treeTable_exportExcel_id']";
	public static String Optimizer_lease_total_qu = "Total Moved Quantity>//input[@id='OPT-OPT_txttotalonoffqty3']";
	public static String Optimizer_lease_Grand_total = "Grand Total>//input[@id='OPT-OPT_txtGrandTotal3_input']";
	public static String Optimizer_Total_summary = "Optimizer_Total_summary>//a[text()='Total Summary']";
	public static String Optimizer_oneWayLease = "One-Way Lease Details>//td[text()='One-Way Lease Details']";
	public static String Optimizer_Summary_Details = "One-Way Lease Details>//td[text()='Summary Details']";
	public static String Optimizer_GrandTotalVal = "One-Way Lease Details>//td[text()='Grand Total']";
	public static String Optimizer_version = "version>(//label[contains(text(),'Version')])[2]";
	public static String Optimizer_surplus_Location = "Optimizer_surplus_Location>(//div[@id='OWS-OWS_treeTable']//div[@col-id='origin'])[6]";
	public static String Optimizer_deficit_location2 = "deficit_location>(//div[@id='OWS-OWS_treeTable']//div[@col-id='delivery'])[6]";
	public static String Surplus_FirstVal = "Surplus_FirstVal>(//div[@id='OWS-OWS_treeTable']//div[@col-id='origin'])[2]";
	public static String Optimizer_surplus_Location1 = "Optimizer_surplus_Location>(//div[@id='OWS-OWS_treeTable']//div[@col-id='origin'])[2]";
	public static String Optimizer_deficit_location3 = "deficit_location>(//div[@id='OWS-OWS_treeTable']//div[@col-id='delivery'])[2]";
	public static String Optimizer_Ys_OPtion = "Optimizer yes OPtion>//button[text()='Yes']";
	public static String Remarks = "Remarks>(//div[@id='OPT-OPT_treeTable4']//span[text()='Remarks'])[1]";
	public static String Optimizer_surplus_Location_5Row = "Optimizer_surplus_Location>(//div[@id='OWS-OWS_treeTable']//div[@col-id='origin'])[5]";
	public static String Optimizer_deficit_location5row = "deficit_location>(//div[@id='OWS-OWS_treeTable']//div[@col-id='delivery'])[5]";
	public static String Scroll_value = "table scroll>//div[@id='OWS-OWS_treeTable_tbl']//div[@ref='eBodyViewport']";
	public static String Close_global = "global close>(//a[@aria-label='Close'])[9]";

	public static String Optimizer_Allocate_Containers5 = "Optimizer_Allocate_Containers>((//div[@row-id='0'])[2]//following::div[@col-id='allocatecntr'])[5]";
	public static String Optimizer_Allocate_Containers_input = "Optimizer_Allocate_Containers>((//div[@row-id='4'])[2]//following::div[@col-id='allocatecntr'])[1]/input";

	public static String Optimizer_Grid_locationfield5 = "Grid record location field1>(//div[@col-id='origin'])[6]";
	public static String Allocate1 = "Allocate1>(//div[@col-id='allocatecntr'])[2]";
	public static String Deficit_Location_name = "Deficit_Location>(//div[@col-id='delivery'])[6]";
	public static String Total_records = "Total_records>//label[@id='OPT-OPT_treeTable1_records_lbl_cnt']";
	public static String Average_cost = "Average_cost>//input[@id='OPT-OPT_txttotalCost2_input']";

	public static String Total_onhire_quantity = "Total on hire quantity>//input[@id='OPT-OPT_txttotalonoffqty']";
	public static String Total_offhire_quantity = "Total off hire quantity>//input[@id='OPT-OPT_txttotalonoffqty1']";
	public static String Total_moved_quantity = "Total moved quantity>//input[@id='OPT-OPT_txttotalqty1']";
	public static String Hire_Total_records = "Hire_Total_records>//label[@id='OPT-OPT_treeTable4_records_lbl_cnt']";
	public static String Hire_avg_cost = "Hire_avg_cost>//input[@id='OPT-OPT_txttotalCost1_input']";
	public static String Hire_grand_total = "Hire_grand_total>//input[@id='OPT-OPT_txtGrandTotal1_input']";

	public static String Onewaylease_total = "Onewaylease_total>//input[@id='OPT-OPT_txttotalqty3']";
	public static String Avg_costperbox = "Onewaylease average cost per box>//input[@id='OPT-OPT_txttotalCost3_input']";
	public static String Onewaylease_count = "Onewaylease total count>//label[@id='OPT-OPT_treeTable5_records_lbl_cnt']";

	public static String Ero_Chart1 = "ERO Chart 1>//*[@id='OPT-OPT_tabeqpchart']";

	public static String On_off_hiresummary = "On_off_hiresummary>//a[text()='On/Off-Hire Summary']";
	public static String On_off_hire_table = "On_off_hire_table>//tbody[@id='OPT-OPT_treeTableOnOffHireSum_data']";

}
