package locators;

public interface ERO_Deviation_Report_Locators {
	public static String session_confirmation1="Already a valid session is active for this login confirm>//span[contains(text(),'Already a valid session is active for this login')]/following::button[@id='confirm']";
	public static String Username_input1="UserName Input field>//input[@id='nfr_login_authname']";
	public static String Password_input1="Password Input field>//input[@id='nfr_login_authid']";
	public static String SignIn1="Sign In button>//button[@id='nfr_login_btnlogin']";

	public static String Searchbox1="Searchbox>//input[@id='nfr_topbar_autocomp_input']";
	public static String Select_Deviation="Select_Deviation>//span[contains(text(),'ERO Deviation Report')]";
	public static String Cancel_Report="Cancel_Report>//button[@id='ERD-ERD_toolbarid-btnTblCancel']";	
	public static String Close_Tab_Report="Close_Tab_Report>(//label[text()='ERO Deviation Report']/following::a)[3]";
	public static String New_Report="New_Report>//button[@id='ERD-ERD_toolbarid-btnTblNew']";
	public static String Create_New_Confirm1="Create_New_Confirm1>//h2[text()='ERO Deviation Report']/following::button[text()='Yes']";
	public static String Search1="Search1>//button[@id='ERD-ERD_btnOptId-ERD_btnOptId']";
	public static String Search2="Search2>//button[@id='ERD-ERD_btnEqpType']";
	public static String Search3="Search3>//button[@id='ERD-ERD_btnOpVer1']";
	public static String Search4="Search4>//button[@id='ERD-ERD_btnOpVer2']";
	public static String Scroll1="Scroll1>(//div[@class='ui-datatable-scrollable-body'])[2]";
	public static String Scroll2="Scroll2>(//div[@class='ui-datatable-scrollable-body'])[3]";
	public static String Deviation_Tab="Deviation_Tab>(//label[text()='ERO Deviation Report'])[1]";
	public static String Version_Number="Version_Number>(//div[@id='ERD-ERD_Colorchange']//following::label)[1]";
	public static String Popup_Msg_Report="Popup_Msg_Report>(//h2[text()='ERO Deviation Report']/following::span)[2]";
	public static String Report_Ques_mark="Report_Ques_mark>(//h2[text()='ERO Deviation Report']/following::span)[1]";
	public static String Information_Icon_Report="Information_Icon_Report>(//*[@id='lrp_cust_growl_container']//span)[1]";
	public static String Error_ID_Search_Popup_Deviation="Error_ID_Search_Popup_Deviation>//*[@class='ui-growl-title']//following::p";
	public static String Click_Search_Report="Click_Search_Report>//button[@id='myBtn']";	 
	public static String Screen_Deviation="Screen_Deviation>//ul[@id='nfr_tabmdl_header']";
	public static String Search_Filed1="Search_Filed1>//input[@id='ERD-ERD_sTxtOptId']";
	public static String Search_Filed2="Search_Filed2>//input[@id='ERD-ERD_sTxtEqp']";
	public static String Search_Filed3="Search_Filed3>//input[@id='ERD-ERD_sTxtOpVer1']";
	public static String Search_Filed4="Search_Filed4>//input[@id='ERD-ERD_sTxtOpVer2']";
	public static String Newtab_confirm_Report="Newtab_confirm_Report>//*[@name='nfr_launch_mdl_in_separatewindow_cnf_form']//a[text()='Yes']";
	public static String Grid_Cell="Grid_Cell>(//tr[@data-ri='0']//following::td[@role='gridcell'])[1]";
	public static String Edit_Field2="Edit_Field2>(//span[text()='Deficit Location']/following::input)[1]";
	public static String Paste_Grid="Paste_Grid>(//tr[@data-ri='0']//following::td[text()='THLCH(OW)'])[1]";
	public static String Search_Close="Search_Close>(//label[text()='ERO Deviation Report']//following::a[@aria-label='Close'])[7]";
	public static String Search_module_Report ="Search_module_Report>//input[@id='nfr_topbar_autocomp_hinput']";
	public static String Click_Ok_Report ="Click_Ok_Report>//h2[text()='ERO Deviation Report']/following::button[text()='Ok']";
	public static String Export_Report ="Export_Report>//button[@id='ERD-ERD_toolbarid-btnTblExport']";
	public static String Filter_1_Report ="Filter_1>(//thead[@id='ERD-ERD_Version1DGrid_head']//following::span[text()='Surplus Location']/following::input)[1]";
	public static String Grid_1_Report ="Grid_1_Report>((//span[text()='Surplus To Deficient Movement']//following::tr)[4]/td)[1]";
	public static String Filter_2_Report ="Filter_2_Report>(//thead[@id='ERD-ERD_Version1DGrid_head']//following::span[text()='Surplus Location']/following::input)[2]";
	public static String Grid_2_Report ="Grid_2_Report>((//span[text()='Surplus To Deficient Movement']//following::tr)[4]/td)[2]";
	public static String Filter_3_Report ="Filter_3_Report>(//span[text()='Quantity']//following::input)[1]";
	public static String Grid_3_Report ="Grid_3_Report>((//span[text()='Surplus To Deficient Movement']//following::tr)[4]/td)[3]";
	public static String Filter_4_Report ="Filter_4_Report>(//span[text()='Cost per Qty(USD']//following::input)[1]";
	public static String Grid_4_Report ="Grid_4_Report>((//span[text()='Surplus To Deficient Movement']//following::tr)[4]/td)[4]";
	public static String ID_Deviation ="ID_Deviation>//span[text()='ID']";
	public static String Search_Optim ="Search_Optim>//button[@id='ERD-ERD_btnOptId2-ERD_btnOptId2']";
	public static String Grid1_1Report ="Grid1_1Report>(//span[text()='Surplus To Deficient Movement']//following::td)[26]";
//	public static String Grid2_2 ="Grid2_2>((//tbody[@id='ERD-ERD_Version2DGrid_data']//following::tr)[2]/td)[1]";
	//public static String Grid2_2 ="Grid2_2>((//tbody[@id='ERD-ERD_Version2DGrid_data']//following::tr)[3]/td)[1]";
	public static String Select_ID_1 ="Select_ID_1>(//div[@col-id='C1'])[3]";
	public static String Total_QTY_1 ="Total_QTY_1>//input[@id='ERD-ERD_txtQuantity1_input']";
	public static String Total_QTY1 ="Total_QTY1>//input[@id='ERD-ERD_txtQuantity1_input']";
	public static String Total_QTY_2 ="Total_QTY_2>//input[@id='ERD-ERD_txtGrdTotal2_input']";
	public static String Total_QTY2 ="Total_QTY2//input[@id='ERD-ERD_txtQuantity2_hinput']";

	public static String Filter_Search ="Filter_Search>//input[@aria-label='Equipment Type Filter Input']";
	public static String Select_ID_2 ="Select_ID_2>(//div[@col-id='C1'])[2]";
	public static String Grid_Data1 ="Grid_Data1>(//tbody[@id='ERD-ERD_Version1DGrid_data']//tr//td[3])[2]";
	public static String Select_EQ ="Select_EQ>(//a[text()='20HC'])[1]";
	public static String Data_Grid1 ="Data_Grid1>(//tbody[@id='OPT-OPT_treeTable_data']//tr//td[4])[5]";
	public static String Row1 ="Row1>//tbody[@id='ERD-ERD_Version1DGrid_data']//tr[1]";
	public static String Row2 ="Row2>//tbody[@id='ERD-ERD_Version2DGrid_data']//tr[1]";
	public static String Quantity_Data2 ="Quantity_Data2>//tbody[@id='ERD-ERD_Version2DGrid_data']//tr//td[4]";
	public static String Quantity_Data1 ="Quantity_Data1>//tbody[@id='ERD-ERD_Version1DGrid_data']//tr//td[4]";
	public static String Grand_Data_Total1 ="Grand_Data_Total1>//input[@id='ERD-ERD_txtGrdTotal1_input']";
	public static String Grand_Data_Total2 ="Grand_Data_Total2>///input[@id='ERD-ERD_txtQuantity2_input']";
	public static String Grand_DataTotal2 ="Grand_Data_Total2>//input[@id='ERD-ERD_txtQuantity2_hinput']";
	public static String Surplus_Location_Textfield ="Surplus_Location_Textfield>(//span[text()='Surplus Location']/following::input)[1]";

}
